### ISSUE TITLE
Can you create autoCompleteTextViews as defined in the Material Specification

### ISSUE THREAD

**Issue by chnsh** [ZieIony/Carbon#1]
http://www.google.com/design/spec/components/text-fields.html#text-fields-auto-complete-text-field

Especially the inset autoCompleteTextView?

**Comment by ZieIony** [comment]
I'm thinking about TextViews in general, so yes, I'll be doing that. Thank you for the idea for the next part of code :)

**Comment by vbauer** [comment]
:+1:

**Comment by ZieIony** [comment]
Phew, the first issue and it took 3 months.

EditTexts are there, with floating labels, counters and pattern validation.

AutoCompleteTextView is in progress, but it works a little bit different than the original one. There's no popup, but an adapter you have to handle manually. Take a look at Autocomplete demo.

I'm closing the issue as technically AutoCompleteTextView is created. I'll be developing it more though.
