### ISSUE TITLE
Overwrite TextView#setTextAppearance

### ISSUE THREAD

**Issue by NeverGivinUp** [ZieIony/Carbon#102]
Currently carbon.widget.TextView supports two custom attributes in the text appearance style -- allCaps and typeface. It does respect those when inflating the TextView from xml. It does not care about them however when a style is set programmatically via the setTextAppearance method. ( I havn't checked if this is the case with other widgets too.)

**Comment by ZieIony** [comment]
You're right, I forgot about setting TextAppearance from code.

**Comment by ZieIony** [comment]
done
