### ISSUE TITLE
Comparison to the new Design Support Library.

### ISSUE THREAD

**Issue by NeverGivinUp** [ZieIony/Carbon#106]
Google extended the support library by com.android.support:design:22.2.0, which offers some [Material Design visuals and motions](http://android-developers.blogspot.ch/2015/05/android-design-support-library.html). Having a comparison of features and feature qualities would be helpful in deciding which library to choose. It also might contain ideas for Carbon API design.

**Comment by ZieIony** [comment]
Good idea. The new Support library is less stable, but has two or three unique features. I should be able to prepare a wiki page or a blogpost with a comparison.

As for ideas, I'm already implementing view anchors for all standard layouts, and pushing content with Snackbar. You can check that by cloning the repo (it's not production quality yet!)

**Comment by ZieIony** [comment]
I wrote an article with a simple comparison between Carbon and Design Support Library. I would like to add something to wiki as well. You can find the article here: https://androidreclib.wordpress.com/2015/06/08/design-support-library-vs-carbon/

**Comment by NeverGivinUp** [comment]
This is a good article. I'd link it (or it's wiki version) in the features section of the Readme.md. 

I'd also add a subject, which will be of interest to many users considering Carbon: Commitment to further development. So far Google has done a very good job specifying material design, but took its time to offer a (still incomplete) implementation library for use on older devices. Developers have witnessed the growth and development of the appcompat library though and are expecting Google to provide and support a more or less complete and stable Material Design compatibility library eventually. (And many have experienced serious bugs that Google tracks for years without fixing them.) Currently Carbon is ahead of Google's MD library. But I think you need to address the question if it will stay ahead of (or on par with) Google's library. Using Carbon vs. using Google's MD library is a long term commitment for a developer. Most developers would like a solid basis for expectations regarding the long term development of Carbon: What is your feature road map? How do you approach backward compatibility to older versions of the Carbon  API? How many years do you plan/promise to fix bugs? How well are you able to reproduce bugs on various Android versions from different vendors (like the the [chart](http://www.reddit.com/r/androiddev/comments/37pv4i/a_quick_chart_on_the_current_fab_bug_across/) in the medium.com article). I think its perfectly all right to disclose that you have limited resources (and cannot spend all of them on Carbon either). Google's not spending too many resources on the MD library either, so far. Google will be around for a while though. And they are committed to Android. Many developers would be more relaxed in using Carbon if they knew your intentions better.

**Comment by ZieIony** [comment]
Done. The article is available online, the comparison is on wiki, I have some plans for the future. Thanks for your help!
