### ISSUE TITLE
RecyclerView.setheader disables shadows for recycler view items

### ISSUE THREAD

**Issue by Rhtyme** [ZieIony/Carbon#107]
Firstly thank you for this great library that I'm using in my app. I'm using recycler view and everything looks fine:
![device-2015-06-04-100000](https://cloud.githubusercontent.com/assets/8341857/7977162/50c27804-0a98-11e5-9737-891ff1c6bf9d.png)
But When I use carbon's 'recyclerView.setHeader(...) method the shadows of recyclerView's children are not visible anymore:
![device-2015-06-04-095801](https://cloud.githubusercontent.com/assets/8341857/7977194/ab004f4e-0a98-11e5-9ded-aa9c2d8945ac.png)

When I scroll up the recycler view, the top child has some shadows like this:

![device-2015-06-04-095841](https://cloud.githubusercontent.com/assets/8341857/7977205/cd4fd420-0a98-11e5-806b-d11e770968d6.png)

Please help me sir, I don't know what I'm doing wrong

**Comment by ZieIony** [comment]
Thanks for your kind words, I'm happy that my library is useful for you!

It's a Carbon's redrawing issue. I'll be able to fix that after the upcomming weekend (4 days off in Poland!). For now you can try to invalidate recycler to force redrawing.

I'm marking this issue as a bug.

**Comment by Rhtyme** [comment]
OK, Thanks for your attention. I'll be waiting.

**Comment by ZieIony** [comment]
Fixed and works for me. The fix is available on master, so you can check that with your code.

**Comment by Rhtyme** [comment]
yes, it works. Thanks for job.
