### ISSUE TITLE
 couldn't find native method

### ISSUE THREAD

**Issue by patelakshay13890** [ZieIony/Carbon#108]
ERROR: couldn't find native method
Requested: Landroid/support/v8/renderscript/RenderScript;._nInit:()V
RegisterNatives failed for 'android/support/v8/renderscript/RenderScript', aborting
Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1)

**Comment by ZieIony** [comment]
Could you please add more details:
- what device are you using?
- what are the steps to reproduce the error
- did you try to restart your device, update the SDK and clear your project?
- was it working before?
- any specific things?

**Comment by ZieIony** [comment]
No answer for 9 days, I'm unable to help without any more information, I'm closing the issue
