### ISSUE TITLE
Load svg from resources

### ISSUE THREAD

**Issue by ZieIony** [ZieIony/Carbon#111]
It should be possible to load an svg as a Drawable from int resId without any special methods and classes

**Comment by jakub-swierk** [comment]
I see three ways to make it work.

1: You need to extend Activity to return Resource class thats extends getDrawable().
Acitivity creates window object thats uses context.
Context are provided by activity (self), and uses to create resources by Resource class.

2: Extend all basic views.

3: Use reflection.

Do you have any other idea?

**Comment by ZieIony** [comment]
1st one is actually very good, but introduces one more configuration step. Either an Activity class or a Context wrapper.
2nd one is pretty easy as I already have all basic views extended.
I'm afraid that I don't understand the last option. I don't want to use reflection as long as it can be done in other way.

**Comment by jakub-swierk** [comment]
About third, if you really extend all views so, we dont need talk about the worst solution.

**Comment by ZieIony** [comment]
It's done using 1st approach for 3rd party libraries and 2nd approach for Carbon widgets.
