### ISSUE TITLE
API compatibilty

### ISSUE THREAD

**Issue by NeverGivinUp** [ZieIony/Carbon#112]
carbon 0.10 has changed two aspects of interface/protocol over carbon 0.9, which present a nuisance (at the least).
1. the RecyclerView API differs from the version, making adjustments necessary. Unless this is absolutely unavoidable, I'd strongly recommend using the original RecyclerView API.
2. LinearLayout expects its children to have a carbon.widget.LinearLayout.LayoutParameter. If, during layout, the children have other parameters, it throws an exception. This is rather painful, when moving to carbon 0.10, as the exception does not tell where the layout parameter is set. Instead it should either decline the use of LayoutParameters of the wrong class, when they are set or preferably wrap/copy them to the right type.

**Comment by ZieIony** [comment]
1. I guess you're thinking about header-related methods. I'll just revert the old methods and mark them as deprecated.
2. LayoutParams are automatically generated by LinearLayout, so replacing android.widget.LinearLayout with carbon.widget.LinearLayout replaces LayoutParams class as well. Could you be more specific about this issue?

**Comment by NeverGivinUp** [comment]
1 Sorry, I should have been specific in that it's about the Adapter, not the View itself.

The signature of android.support.v7.RecyclerView.Adapter is 
  public static abstract class Adapter<VH extends ViewHolder> {
   public abstract VH onCreateViewHolder(ViewGroup parent, int viewType);
  public abstract void onBindViewHolder(VH holder, int position);
.... some concrete methods
}

The signature of carbon.widget.RecyclerView.Adapter is 
 public abstract static class Adapter<VH extends ViewHolder, I> extends android.support.v7.widget.RecyclerView.Adapter<VH> {
... the support methods
 public abstract I getItem(int var1);
}

2 When you have View v = new View(context); and carbon.widget.LinearLayout l = new carbon.widget.LinearLayout(context); and l.addChild(v); works very well, but l.addChild(v, new android.widget.LinearLayout.LayoutParams(WRAP_CONTENT, WRAP_CONTENT); produces an exception during layout. Same with LayoutParams of super types of android.widget.LinearLayout. The android framework converts/wraps/copies super type LayoutParams to the fitting type filling in default values, where they are missing.

**Comment by ZieIony** [comment]
1. It's used internally by PopupMenu. You can stay with `android.support.v7.RecyclerView.Adapter`. The best way to have both solutions is to use default generic types. It should be possible, but I have to check that.
2. Right, this is a bug.

**Comment by NeverGivinUp** [comment]
If the carbon Recyclerview Adapter is meant for internal use, I'd recommend hiding it, making it's constructor package private or otherwise marking it, so people don't think they are supposed to use it. For me personally a note in Javadoc would not be not enough of a warning.

**Comment by ZieIony** [comment]
Right. I guess I'll just leave that class as it is, to not introduce more confusion about it. I just have to pay more attention to changes in the future.

Javadoc and the documentation in general is an another story. I'm aware of that the documentation is very poor, but it takes a lot of time to prepare everything I would like to have.

**Comment by NeverGivinUp** [comment]
Uh, my remark on the javadoc wasn't meant as criticism. I meant, that I usually don't read javadoc before I use the library. I rely on the names and signatures to guide me. Only when things seem not to make sense, I start reading javadoc. That's why I Javadoc is not enough warning for me _not_ to use a class or method.

**Comment by ZieIony** [comment]
Yes, I know :)

I'm thinking about javadocs just because. Carbon still needs more documentation, release notes and samples (not sample code, but complete samples with comments and screenshots).
