### ISSUE TITLE
Using the snackbar with a transparent navigation bar (on lollipop)

### ISSUE THREAD

**Issue by NeverGivinUp** [ZieIony/Carbon#114]
Snackbars want to be touched. In fact that's the whole point. Otherwise they would be toasts. 

On Lollipop devices I paint my status bar as well as my navigation bar in the dark shade of my app's primary color. I do so using a variation of the ScrimInsetsFrameLayout. This layout implements View#fitSystemWindows(Rect), allowing the view to draw whatever it likes in the system spaces. The view can draw there but not receive touches. The system grabs any touches.

Currently Snackbars consider the whole window content as their playground, expecting it to be between, not underneath the status and navigation bar. This works great on pre-Lollipop devices and on Lollipop devices that don't use a transparent navigation bar. On Lollipop devices, I need a way to tell the Snackbar that the navigation bar is transparent and and need it to avoid that area. I suppose it wouldn't be feasible to let it find out itself.

**Comment by NeverGivinUp** [comment]
As it turns out this is another bug in the user. The navigation bar is not supposed to be colored

[When you customize the navigation and status bars, either make them both transparent or modify only the status bar. The navigation bar should remain black in all other cases.](https://developer.android.com/training/material/theme.html)

**Comment by ZieIony** [comment]
I had no time to take a closer look, but I wanted to improve something related to this issue. I'm reopening the issue to keep that in mind.

**Comment by ZieIony** [comment]
Snackbar now behaves correctly in the described case (appears above or next to translucent navigation bar)
