### ISSUE TITLE
deprecations need explanation

### ISSUE THREAD

**Issue by NeverGivinUp** [ZieIony/Carbon#115]
This is a general documentation issue, but a more practically relevant one. There are several deprecated classes (e.g. SVGView and ImageActionButton) but they give not context. 

What I really need to know about deprecations is 
1. why this class or method has been deprecated and 
2. what to do instead of using it.

**Comment by ZieIony** [comment]
Good point

**Comment by ZieIony** [comment]
Deprecations are now commented with proper JavaDocs. I'll try to remember about that and add JavaDocs while working on the lib.
