### ISSUE TITLE
How to  implement the fab "quick return" pattern?

### ISSUE THREAD

**Issue by NeverGivinUp** [ZieIony/Carbon#118]
Do you have any suggestions on how to implement the "quick return" pattern, i.e. hiding the floating action button on scrolling down and showing it on scrolling up? Especially considering the button will be connected to layouts of different types ScrollView, RecyclerView, ListView etc.

**Comment by ZieIony** [comment]
Each view is a little bit different, so I don't have anything universal.
For a sample with RecyclerView see the 'Quick Return' demo in Demos section. The key part goes like that:

``` java
recyclerView.addOnScrollListener(new android.support.v7.widget.RecyclerView.OnScrollListener() {
            int yscroll = 0;

            @Override
            public void onScrolled(android.support.v7.widget.RecyclerView recyclerView, int dx, int dy) {
                super.onScrolled(recyclerView, dx, dy);
                if (fab.getVisibility() == View.VISIBLE && fab.getAnimator() == null && yscroll > 50 * Carbon.getDip(getApplicationContext())) {
                    yscroll = 0;
                    fab.setVisibility(View.GONE);
                    toolbar.setVisibility(View.GONE);
                }
                if (fab.getVisibility() != View.VISIBLE && fab.getAnimator() == null && yscroll < -50 * Carbon.getDip(getApplicationContext())) {
                    yscroll = 0;
                    fab.setVisibility(View.VISIBLE);
                    toolbar.setVisibility(View.VISIBLE);
                }
                if (Math.signum(dy) != Math.signum(yscroll))
                    yscroll = 0;
                yscroll += dy;
            }
        });
```

Carbon doesn't have any suport for that, because it's pretty easy to implement and each implementation behaves a little bit different (for example hides items only when scrolling is faster than X).

**Comment by NeverGivinUp** [comment]
Thanks, that's very helpful :-)
