### ISSUE TITLE
ImageView#setVisibility should work even if previous animation has not finished

### ISSUE THREAD

**Issue by NeverGivinUp** [ZieIony/Carbon#123]
Currently ImageView checks getVisibility() to determine its behaviour but calls super.setVisibility() only after the animation has finished. In some circumstances I need to set visibility to INVISIBLE first and set it to VISIBLE in a OnPreDrawListener. The first animation did not have time to finish. On setting it to visible, the visibility (as determined by getVisibility()) seems to already be VISIBLE. The method just returns. The visibility becomes/stays INVISIBLE and neither the Imageview nor its appearance animation is shown.

**Comment by ZieIony** [comment]
I've added animation cancelling. If there's an animation running, a consecutive setVisibility() call will cancel that animation and start a new one. That doesn't execute the super.setVisibility() but only cancel the animation. If you wish to change visibility immediately, change animation to Style.None (setVisibility() will execute and return immediately) or call setVisibilityImmediate()

**Comment by NeverGivinUp** [comment]
Great. I've added a note to the Reference https://github.com/ZieIony/Carbon/wiki/ImageView
