### ISSUE TITLE
EditText does not show underline

### ISSUE THREAD

**Issue by NeverGivinUp** [ZieIony/Carbon#125]
I'm not sure if this is a styling configuration problem or if it goes deeper.

**Comment by ZieIony** [comment]
Were you able to solve this issue? If not, could you please elaborate? I'm unable to reproduce it.

**Comment by NeverGivinUp** [comment]
Actually I'm using MaterialEditText (a different library). I used your carbon EditText only by mistake, because I was blindly replacing android widgets by carbon widgets. I just reported it for the sake of ratting out another bug. If you cannot reproduce it's OK for me to just close it.

**Comment by ZieIony** [comment]
Let's just close it then. If it's a real deal, someone will report it again.
