### ISSUE TITLE
ViewPropertyAnimator breaks ImageActionButton elevation shadow

### ISSUE THREAD

**Issue by Ludomancer** [ZieIony/Carbon#126]
I have the below code that animates the ImageActionButton to the middle or to the right of the screen. When it is animated, the shadow is not updated on the last frame and it stays a couple of pixels off from the actual ImageActionButton. ~~I could not take n Screenshot because as soon as I've bring the screenshot option in Android, ImageActionButton (I think) invalidates it self, and the shadow position is corrected.~~

Got the screenshot by using Android Studio: [Screenshot](http://i.imgur.com/78DRTH3.png)

I have also tried to remove setInterpolator thinking maybe overshoot causes issue but it had no effect.

If I call invalidateShadow at the end of the animation it fixes the problem. (The shadow is still misaligned for a split second before the event fires up and invalidates it.)  But obviously this is more of a workaround than a solution.

``` java

public void onCreate(Bundle savedInstanceState)
    {
....

  mFabAnimator = mFab.animate();
        mFabAnimator.setInterpolator(new OvershootInterpolator());
....
}

private void moveFabToCenter(boolean animate)
    {
        DisplayMetrics dm = new DisplayMetrics();
        this.getWindowManager().getDefaultDisplay().getMetrics(dm);

        int xDest = dm.widthPixels / 2;
        xDest -= (mFab.getMeasuredWidth() / 2);

        if (animate) mFabAnimator.x(xDest).setDuration(500).start();
        else mFab.setX(xDest);
    }

    private void moveFabToBottomRight(boolean animate)
    {
        DisplayMetrics dm = new DisplayMetrics();
        this.getWindowManager().getDefaultDisplay().getMetrics(dm);

        int xDest = dm.widthPixels;
        float d = getResources().getDisplayMetrics().density;
        xDest -= mFab.getMeasuredWidth() + ((RelativeLayout.LayoutParams) mFab.getLayoutParams()).rightMargin / 2 * d;

        if (animate) mFabAnimator.x(xDest).setDuration(500).start();
        else mFab.setX(xDest);
    }
```

Fab Layout

``` xml

<carbon.widget.RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:app="http://schemas.android.com/apk/res-auto"
                xmlns:fab="http://schemas.android.com/apk/res-auto"
                android:layout_width="match_parent"
                android:layout_height="match_parent">
 <carbon.widget.ImageActionButton
        android:id="@+id/fab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerHorizontal="true"
        android:layout_marginBottom="@dimen/fab_margin"
        android:layout_marginRight="@dimen/fab_margin"
        android:background="@color/falmate_material_secondary"
        android:src="@drawable/ic_action_camera"
        app:carbon_elevation="@dimen/carbon_elevationHigh"
        android:layout_above="@+id/camera_content_layout"
        />

</carbon.widget.RelativeLayout>
```

**Comment by Ludomancer** [comment]
If that helps in anyway, I have solved the issue by using ValueAnimator instead of PropertyAnimator and calling postInvalidate on the views parent on every Update.

**Comment by ZieIony** [comment]
This is pretty much the correct solution. Shadow in Carbon is drawn by view's parent, so you have to invalidate parent as well. This is what AnimUtils animators are doing. I've added set of transformation methods to all Carbon widgets.
