### ISSUE TITLE
Could not find class 'carbon.drawable.RippleDrawableLollipop'.

### ISSUE THREAD

**Issue by Ludomancer** [ZieIony/Carbon#127]
Dalvikvm throws following exceptions every time the app is launched. They do not create any problems in the app itself, but might worth checking out.

08-11 19:08:58.381  26286-26286/com.appname.appnameE/dalvikvm﹕ Could not find class 'carbon.drawable.RippleDrawableLollipop', referenced from method carbon.Carbon.initRippleDrawable
08-11 19:09:00.616  26286-26286/com.appname.appnameE/dalvikvm﹕ Could not find class 'carbon.shadow.ShadowShape$1', referenced from method carbon.shadow.ShadowShape.<clinit>

**Comment by ZieIony** [comment]
Thanks for reporting that!

Dalvik tries to load every single class it encounters. Both classes you mentioned are directly referencing 5.+ system classes, which are unavailable on older platforms. These issues are harmless, because on older Android versions these classes remain unreferenced.

**Comment by gorodechnyj** [comment]
And in my case this leads to crash on API 15 emulator. The crash happens when I open DrawerLayout. I also use ActionBarDrawerToggle with it:

```
actionBarDrawerToggle = new android.support.v7.app.ctionBarDrawerToggle(...
drawerLayout.setDrawerListener(actionBarDrawerToggle);
actionBarDrawerToggle.syncState();
```

09-02 19:09:42.803    9592-9592/com.masani E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.VerifyError: carbon/shadow/ShadowGenerator
            at carbon.widget.LinearLayout.getShadow(LinearLayout.java:489)

**Comment by ZieIony** [comment]
That is a different error. I've opened an issue for tracking that. See #134
