### ISSUE TITLE
consider tweaked SVG library

### ISSUE THREAD

**Issue by NeverGivinUp** [ZieIony/Carbon#128]
Loading SVGs can be pretty slow. SVG was not created being read on the fly. And work on AndroidSVG seems not progressed for over a year. 

Consider using `compile 'de.greenrobot:androidsvg:1.2.2-beta-1-tweaked-2'`. No need to the java code necessary. The library [claims](https://code.google.com/r/markus-performance-optimization/) to be considerably faster for some SVGs (though I wasn't able to experience that subjectively).

**Comment by ZieIony** [comment]
Sounds good and works pretty well. Let's give it a shot, I've updated the lib.
