### ISSUE TITLE
Toolbar - make a getIcon method

### ISSUE THREAD

**Issue by divanshugarg** [ZieIony/Carbon#131]
There is no getIcon in the carbon.widget.Toolbar. I would like to customize the onclick behaviour of the icon to open up a navigation drawer instead. That isnt possible with the current restrictions. It would be great if you could provide a getter for the 'icon' in Toolbar.

**Comment by ZieIony** [comment]
Unfortunatelly, currently I'm unable to address your issue as I have no access to my workspace right now. You have three options:
1. Get the icon view using findViewById:

``` Java
Toolbat toolbar;
ImageView icon = (ImageView) toolbar.findViewById(carbon.R.id.carbon_icon);
```
1. Add the method by yourself and make a pull request so everyone can get the updated version.
2. Wait for me to make changes.

**Comment by ZieIony** [comment]
I've added two methods:

``` Java
    public Drawable getIcon(){
        return icon.getDrawable();
    }

    public View getIconView(){
        return icon;
    }
```
