### ISSUE TITLE
circular_progressbar remain  some color dots

### ISSUE THREAD

**Issue by fourcels** [ZieIony/Carbon#136]
Android version: **4.2.2**

![screenshot_2015-09-14-14-27-24_2](https://cloud.githubusercontent.com/assets/1042568/9844756/90095928-5af8-11e5-863d-9ae748595c49.png)

I have tried to  edit **carbon.widget.drawable.CircularProgressDrawable.java**, **draw** method

``` java
boundsF.inset(width / 2 + barPadding , width / 2 + barPadding );
```

to

``` java
boundsF.inset(width / 2 + barPadding + 0.5f , width / 2 + barPadding + 0.5f);
```

the color dots disapear

**Comment by ZieIony** [comment]
I was aware of this issue for a long time, but I had no idea how to correctly fix it. Now it should be better.
