### ISSUE TITLE
Ripple & Shadows are not displayed

### ISSUE THREAD

**Issue by ghost** [ZieIony/Carbon#14]
The ripple is not displayed when I add a background color to the button & the shadows are not displayed.

```
    <carbon.widget.Button
        android:text="Details"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentEnd="true"
        android:layout_alignParentRight="true"
        android:layout_marginRight="10dp"
        app:carbon_cornerRadius="2dp"
        android:textColor="@color/white"
        android:background="@color/gold_color"/>
```

In the build.gradle

```
    defaultConfig {
        applicationId "wuugames.com.appdominals"
        minSdkVersion 14
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
        renderscriptTargetApi 20
        renderscriptSupportModeEnabled true
    }
```

P.S I'm extending from ActionBarActivity, so can that be the issue? 

Thanks.

**Comment by ZieIony** [comment]
Shadows are drawn by layouts, so you have to wrap _carbon.widget.Button_ in _carbon.widget.LinearLayout_ or _carbon.widget.FrameLayout_ or _carbon.widget.RelativeLayout_. Like this:

```
<carbon.widget.LinearLayout
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">
    <carbon.widget.Button
        android:text="Button"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />
</carbon.widget.LinearLayout>
```

Most of the views have _carbon_elevation_ attribute, which controls size and blurriness of a shadow. It is set by a carbon theme to 2dp by default. Activity doesn't matter. You only have to set one of carbon themes to get all features enabled by default.

Your build.gradle file is looking fine. What else can help is the device model and system version you're testing on (for example Galaxy S 3 with Samsung's Android 4.3). Also please make sure that the ripple is really gone by setting different colors or backgrounds and longpressing the Button. You can specify a ripple color by yourself using _carbon_rippleColor_ attribute of that Button.

**Comment by ZieIony** [comment]
I'm closing the issue as it's 7 days old with no responses.

**Comment by ghost** [comment]
Hey there,

Yes sorry for the delayed reply, your suggestion worked perfectly by wrapping the view in a parent container.

But now I have another question. I can't set a background color or elevation to the cabron.widget.RelativeLayout view. It works great with the cabron.widget.LinearLayout but not with the RelativeLayout version. Do you have any suggestion for this one?

(The below view is inside a carbon.widget.RelativeLayout parent container).

```
 <carbon.widget.RelativeLayout
            android:layout_width="fill_parent"
            android:layout_height="wrap_content"
            android:background="@color/white"
            app:carbon_elevation="@dimen/low_elevation"
            >
```

**Comment by ZieIony** [comment]
I'm sorry, but this is a known issue and I cannot help you right now in any other way than just suggest using LinearLayout or wrapping your layout in another LinearLayout. This one is going to be fixed in the next release, most likely in 2-3 days.

For more details see: #15 

I'm moving the discussion to a new issue.

**Comment by ghost** [comment]
It's OK, I can wait. 

You are doing a great job here. I have replaced all the views in my layouts with the ones from Carbon and they are great. Thank you for this :+1:

**Comment by ZieIony** [comment]
Wow, thank you very much for your kind words! I really appreciate that. The release with most recent changes (including bugfixes) is ready. Please check if the updated version works for you and let me know.

As I mentioned, I've opened an issue for the discussion about this bug. See: #20

**Comment by ghost** [comment]
Yes, I can confirm now that carbon.widget.RelativeLayout is working properly. Good job.

That being said, I have stumbled upon another issue. When a carbon.widget.LinearLayout or  carbon.widget.RelativeLayout contains a carbon.widget.Button, the view is not displayed properly as you can see in the below screenshot:

![carbon_bug](https://cloud.githubusercontent.com/assets/5017425/6333343/8955f368-bb8c-11e4-9dfb-253191264154.png)

Here is the XML code for this layout:

```
<?xml version="1.0" encoding="utf-8"?>
<carbon.widget.RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    >

    <carbon.widget.LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_margin="@dimen/content_margin"
        android:background="@color/white"
        android:orientation="vertical"
        app:carbon_cornerRadius="@dimen/mid_radius"
        app:carbon_elevation="@dimen/low_elevation"
        >

        <carbon.widget.Button
            android:id="@+id/sign_up_button"
            android:layout_width="fill_parent"
            android:layout_height="46dp"
            android:layout_marginTop="18dp"
            android:layout_marginLeft="@dimen/content_margin"
            android:layout_marginRight="@dimen/content_margin"
            android:background="@color/secondary_accent"
            android:text="@string/sign_up_button_text_login_sign_up_activity"
            android:textColor="@color/white"
            app:carbon_cornerRadius="@dimen/mid_radius"
            app:carbon_elevation="@dimen/low_elevation"
            app:carbon_rippleColor="@color/ripple_color"
            />

        <carbon.widget.Button
            android:id="@+id/login_button"
            android:layout_width="fill_parent"
            android:layout_height="46dp"
            android:layout_marginTop="10dp"
            android:layout_marginLeft="@dimen/content_margin"
            android:layout_marginRight="@dimen/content_margin"
            android:background="@color/primary_accent"
            android:text="@string/login_button_text_login_sign_up_activity"
            android:textColor="@color/white"
            app:carbon_cornerRadius="@dimen/mid_radius"
            app:carbon_elevation="@dimen/low_elevation"
            app:carbon_rippleColor="@color/ripple_color"
            android:layout_marginBottom="@dimen/content_margin"
            />

    </carbon.widget.LinearLayout>


</carbon.widget.RelativeLayout>
```

**Comment by ZieIony** [comment]
I must admit i really like this bug. Due to a Paint object reusing, the layout was drawn with 50% alpha. This release has several bugs due to major refactoring and lots of changes. I just pushed a bugfix release. It's called 0.6.3.1
