### ISSUE TITLE
TextView in layout with a ripple shows a ripple as well

### ISSUE THREAD

**Issue by ZieIony** [ZieIony/Carbon#144]

**Comment by CrandellWS** [comment]
How can I duplicate this bug?

**Comment by ZieIony** [comment]
Place a TextView in a layout with a ripple. Spotted long time ago on Galaxy Nexus with Android 4.3

**Comment by ZieIony** [comment]
I'm unable to reproduce now. Maybe it was fixed by update to RippleDrawable

**Comment by CrandellWS** [comment]
I am also unable to reproduce the error...assumed fixed until it can be
reproduced seems to be best course of action
