### ISSUE TITLE
Button elevation doesn't work

### ISSUE THREAD

**Issue by HectorFGarcia** [ZieIony/Carbon#152]
I'm using app:carbon_elevation="@dimen/carbon_elevationMax" on a carbon.widget.Button but nothing happens, there isn't any shadow. The other stuff like ripple works fine.

I'm working with API 14. What am I missing?

**Comment by ZieIony** [comment]
Are you using Carbon layouts? You have to replace android.widget.\* layouts with carbon.widget.\* counterparts. It's not the Button what is drawing its shadow but a parent layout.

**Comment by HectorFGarcia** [comment]
Oops, sorry, my bad, I didn't know that. Now it's working perfectly. Thank you!
