### ISSUE TITLE
Rtl support 

### ISSUE THREAD

**Issue by ayalma** [ZieIony/Carbon#156]
hi friend ,
can you add support for right to left language  like Persian or Arabic ? 
if any help requested i can help you for that .

**Comment by ZieIony** [comment]
Any help would be greatly appreciated! Feel free to point out all broken widgets and layouts you spotted. 

I was thinking about RTL support for a long time, but nobody asked, so I put that away. I've never used any of these languages, so I'm not sure which things should be inverted. Like, for example, the check graphics in CheckBox?

**Comment by ZieIony** [comment]
Carbon in most cases supports RTL layouts without any changes, because it uses Android widgets as a base. I've added suport for Toolbar and TableLayout. If you notice that something is not working as expected, please open another issue for that specific thing. Attach a screenshot and a short explanation.

**Comment by ayalma** [comment]
hi again , and sorry for late.
android only support layout direction in api 17 and up . and this is the real problem .

**Comment by ZieIony** [comment]
You're right. It's a large task and I'm not sure if I can backport directionality to older platforms. I would have to reimplement layouting, directionality attributes, text drawing and many other things. It could break low-level View compatibility with other libraries and built-in Android UI.

For now Carbon supports RTL only if it's supported by the system.

I'm reopening this issue to keep it in mind.

**Comment by ayalma** [comment]
hi ,
i do this work in other way in my own app before and ill hope it can be done here.
1. i create Utility class with RtlUtil name :

```
public class RtlUtils
{

    private static final Set<String> RTL;

    static
    {
        Set<String> lang = new HashSet<String>();
        lang.add("ar"); // Arabic
        lang.add("dv"); // Divehi
        lang.add("fa"); // Persian (Farsi)
        lang.add("ha"); // Hausa
        lang.add("he"); // Hebrew
        lang.add("iw"); // Hebrew (old code)
        lang.add("ji"); // Yiddish (old code)
        lang.add("ps"); // Pashto, Pushto
        lang.add("ur"); // Urdu
        lang.add("yi"); // Yiddish
        RTL = Collections.unmodifiableSet(lang);
    }
    public static boolean isRTL(Context context){
        return isRTL(context.getResources().getConfiguration().locale);
    }
    public static boolean isRTL(Locale locale)
    {
        if(locale == null)
            return false;

        // Character.getDirectionality(locale.getDisplayName().charAt(0))
        // can lead to NPE (Java 7 bug)
        // https://bugs.openjdk.java.net/browse/JDK-6992272?page=com.atlassian.streams.streams-jira-plugin:activity-stream-issue-tab
        // using hard coded list of locale instead
        return RTL.contains(locale.getLanguage());
    }
}
```
1. then i add other xml layout for existing layout like ,  this one for navigation view.
   its your default nav row xml layout output in  api < 17   device

![nav_row](https://cloud.githubusercontent.com/assets/15701316/12164218/3927642a-b529-11e5-858a-6ed89be8f2b1.png)

and i add this one  as  rtl nav row
![nav_row-rtl](https://cloud.githubusercontent.com/assets/15701316/12164364/3838c954-b52a-11e5-867f-1ecde73f24fc.png)

with this xml file

```
<?xml version="1.0" encoding="utf-8"?>
<carbon.widget.LinearLayout
    android:layout_height="wrap_content"
    android:layout_width="match_parent"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:clickable="true"
    android:focusable="true">
    <carbon.widget.RelativeLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        app:carbon_rippleColor="?attr/carbon_rippleColor"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
       >
        <carbon.widget.TextView
            android:layout_alignParentLeft="true"
            android:layout_alignParentTop="true"
            android:layout_toLeftOf="@+id/carbon_itemIcon"
            android:paddingLeft="@dimen/carbon_padding"
            android:paddingRight="@dimen/carbon_padding"
            android:textSize="25sp"
            android:text="سطر تستی"
            android:id="@+id/carbon_itemText"
            android:gravity="center_vertical"
            android:layout_width="match_parent"
            android:layout_toRightOf="@+id/carbon_itemIcon"
            android:layout_height="@dimen/carbon_toolbarHeight" />
        <carbon.widget.ImageView
            android:layout_alignParentTop="true"
            android:layout_alignParentRight="true"
            app:carbon_tint="?attr/colorAccent"
            android:id="@+id/carbon_itemIcon"
            android:padding="@dimen/carbon_padding"
            android:layout_width="@dimen/carbon_toolbarHeight"
            android:layout_height="@dimen/carbon_toolbarHeight"
            android:background="@android:drawable/ic_delete"/>

    </carbon.widget.RelativeLayout>


</carbon.widget.LinearLayout>
```

and when i going to inflate navigation layout i inflate it in below way:

```
 if (Build.VERSION.SDK_INT < Build.VERSION_CODES.JELLY_BEAN_MR1 && RtlUtils.isRTL(parent.getContext())) {
                    view = inflater.inflate(R.layout.carbon_navigation_row_rtl, parent, false);

                } else
                    view = inflater.inflate(R.layout.carbon_navigation_row, parent, false);
```

thank you.

**Comment by ZieIony** [comment]
I understand your approach, but I would like to have something more universal. Picking rtl or ltr layout works well with your specific cases, but a user may want to use a generic layout with items ordered using toEndOf, gravity="start", etc. A good library should provide a generic way of layouting for both directionalities.

As for your directionality detection - Locale class has some definitions which may be useful. You may find this code http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/5.1.1_r1/android/view/View.java/#13194 interesting. I'm not sure if that could be easily backported for older Androids.

**Comment by ZieIony** [comment]
Seems like detection and layouts are not the real problem. EditText is much worse with all these weird selection/edition behaviors when mixing languages. Unfortunately I won't be able to backport that.
