### ISSUE TITLE
LinearLayout ripple effect

### ISSUE THREAD

**Issue by IlyaMyasoedov** [ZieIony/Carbon#157]
Thanks for your project!!! It's great.
In samples there are ripple animations for buttons and imageViews, but i haven't found any animations for relativelayouts and linearlayouts. Could you suggest to me how to add ripple effects for these views?

**Comment by ayalma** [comment]
hi , you can add  this lines to relative or linear or other layout or widget for getting ripple effect:

```
app:carbon_rippleColor="?attr/carbon_rippleColor"
android:clickable="true"
```

something like that : 

```
<carbon.widget.RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:divider="@color/divider"
        android:clickable="true"
        app:carbon_rippleColor="#252525">
       <!--other layout or widget-->
</carbon.widget.RelativeLayout>
```

**Comment by IlyaMyasoedov** [comment]
Thanks for your fast answer!!! 
Best regards

**Comment by asif3593** [comment]
have we need to add any depedency??
