### ISSUE TITLE
Persistent Floating Labels for Edit Texts

### ISSUE THREAD

**Issue by singhdd93** [ZieIony/Carbon#158]
How do I make the floating label persistent for Edit Texts. I  mean I want the floating label to appear even after I lose focus if it has Text

**Comment by ayalma** [comment]
this is not possible from outside of library because that library following google guide line for hiding floating label . but you can download all library and change this part of code in EditText to achieve what you wanted. 

```
        if (showFloatingLabel)
            animateFloatingLabel(isFocused() && s.length() > 0); 
```

to 

```
        if (showFloatingLabel)
            animateFloatingLabel( s.length() > 0);
```

in this method 

```
private void validateInternal()
{}
```

and 
`animateFloatingLabel(focused && getText().length() > 0);`
to 
`animateFloatingLabel(getText().length() > 0);`
in this method of EditText

```
onFocusChanged(){}
```

**Comment by singhdd93** [comment]
Thanks for reply.
You say that lib is following google guidelines but I find it opposite.
Check the link below
https://www.google.co.in/design/spec/components/text-fields.html#text-fields-floating-labels

According to this image on the link 
![Image](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3dWFoM3V0NldkWFU/components_textfields_labels3.png)
The focused EditText shows label in accentColor while not focused one shows it normally.

**Comment by ayalma** [comment]
However I can't change this library but I do what I said in comment and
it  worked.

**Comment by singhdd93** [comment]
I have already done that. Thanks a lot. 
Just want the dev to know, so that he can update the lib (if required)

BTW Its nice to see people other than dev are also helping here :+1: :smile:

**Comment by ZieIony** [comment]
Yes, this is really nice to see the users helping dach other :)

Thanks for the ticket. The persistent label seems to be a nice addition.

**Comment by ZieIony** [comment]
Done, the code is in repository and will be available in the upcomming release. To get it know use jitpack.io.

EditText now features a new attribute:

```
<attr name="carbon_label" format="enum">
            <enum name="floating" value="0"/>
            <enum name="persistent" value="1"/>
            <enum name="hint" value="2"/>
        </attr>
```

carbon_floatingLabel is deprecated, works, is overriden by carbon_label if specified.
