### ISSUE TITLE
edit text pop up menu 

### ISSUE THREAD

**Issue by ayalma** [ZieIony/Carbon#159]
hi ,
when i do long press on edit text when pop up  showed, the all text going to be unselected and then copy or paste and other button don't work as expected  from them
sorry for bad english!

**Comment by ZieIony** [comment]
Thanks for the issue. EditText is still fresh and has some bugs, but I'm working on making it better.

**Comment by ZieIony** [comment]
I just pushed the fix. It works on my phone, but each manufacturer has their own implementation, so I'm not sure if it's truly fixed.

**Comment by ZieIony** [comment]
10 days without answer, so I assume that it's working. Let's close this one and eventually open a new issue for specific issue.

**Comment by ayalma** [comment]
Sorry for late i'm working on my  university final project .
Old problem steel exist and the new problem is that pup showing with double
click instead of long press . sorry

**Comment by ZieIony** [comment]
What device and Android version are you using?

**Comment by ayalma** [comment]
Huawei g730 Android 4.2.2

**Comment by ikasapoglu** [comment]
hi, firstly I'm really so sorry for my bad english and I know; it shouldn't be here(I didn't find your email adress) but I need your help so much.. My problem such as this [link](http://stackoverflow.com/questions/34847696/displaying-a-context-menu-for-selected-text)`

(Actually it's my problem, I wanted to my friend for open the solution cause my account has been banned :/)

Can I do this with your edittext pop-up code ?

Thank you for reading.. Hopefuly you can help me, I'm sorry about that again.

**Comment by ZieIony** [comment]
Please don't ask non-related questions in existing issues. Always add a new one. If you wish to discuss things, feel free to join Carbon's community and add a new thread there: https://plus.google.com/communities/111973718340428039040 . And short answer to your question is - yes, you can do that with my popup code, but Carbon handles action menus as well and you don't need that, so I think that with simple popups it can be even easier.

**Comment by ZieIony** [comment]
EditText with that fancy popup menu was moved to beta package long time ago. The official implementation doesn't have that menu at all. Because of that this issue is no longer relevant. I'm going to add a task for adding that menu to the enchancements list in the project.
