### ISSUE TITLE
new Layout 

### ISSUE THREAD

**Issue by ayalma** [ZieIony/Carbon#162]
can you add support for android.support.design.widget.AppBarLayout , android.support.design.widget.CollapsingToolbarLayout, android.support.design.widget.CoordinatorLayout and android.support.v4.widget.NestedScrollView 
i implement shadow and ripple for cordinator and appbar but seems it not working.
thanks.

**Comment by ZieIony** [comment]
I'm not sure if these classes should be part of Carbon. I don't really like these components. There's good number of known issues with them.

Nevertheless this article and code should help you:
https://androidreclib.wordpress.com/2015/12/23/lets-port-design-support-library-to-carbon/
https://github.com/ZieIony/cheesecarbon

**Comment by ZieIony** [comment]
I've implemented Carbon features for Design Support Library classes, but I wouldn't call it finished yet. If you wish, you can test them and see if it's what you were looking for. Design classes are in beta package for now.

**Comment by CrandellWS** [comment]
Just need to drop in a line:

https://github.com/ZieIony/Carbon/pull/194

**Comment by ayalma** [comment]
Thank you for porting this layouts . i trying to use them in my applicatoin.

**Comment by ZieIony** [comment]
These layouts are not finished yet, so I wouldn't close this issue. Especially Toolbar is not working as I would like it to.

**Comment by ZieIony** [comment]
Moved to the project
