### ISSUE TITLE
Renderscript support mode is not currently supported with renderscript target 21+

### ISSUE THREAD

**Issue by devflow** [ZieIony/Carbon#165]
Yes. i know it was warning. 

but when i update `com.android.tools.build:gradle` to `2.0.0-alpha3`, this warning changed to the error.

I can't continue compiling.

error message 

```
Error:A problem occurred configuring project ':app'.
> Renderscript support mode is not currently supported with renderscript target 21+
```

right now, my temporary build config :

```
renderscriptTargetApi 20
renderscriptSupportModeEnabled true
```

**Comment by devflow** [comment]
are we will follow this wasabeef's commit?

https://github.com/wasabeef/Blurry/commit/1d7aac82d5715ff9169cadc5ef0a525a8522b961

**Comment by ZieIony** [comment]
Yes. I would like to see a real solution from Google, but for now, to support all platforms we have to use renderScript API 20
