### ISSUE TITLE
EditText ColorStateList  tint == null

### ISSUE THREAD

**Issue by taosimple** [ZieIony/Carbon#166]
hello! 
I user carbon , it more flexible and easy use than google's
I import carbon as a lib in my project, when i use EditText, I receive a excepiton:

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.res.ColorStateList.getColorForState(int[], int)' on a null object reference
```

it occur at line 257:

```
labelPaint.setColor(!valid ? errorColor : tint.getColorForState(new int[]{android.R.attr.state_focused}, 0xff00ff00));
```

`ColorStateList tint == null`

it very strange , because you sample project is normal. I don't know why , I don't change EditText at all.

**Comment by ZieIony** [comment]
Are you, by any Chance, using the constructor EditText(Context) in your code?

Which version are you using?

Are you using one of the Carbon's themes?

Could you please post some code how are you using EditText?

**Comment by NamtarR** [comment]
I had the same issue when setting EditText tint in xml like that:
`
app:carbon_tint="@null"
`
And the app crashed on trying to inflate the xml with the similar exception.

**Comment by taosimple** [comment]
@ZieIony I find it , I don't apply theme `carbon_Theme.Light.NoActionBar` in my project

**Comment by ZieIony** [comment]
Cool :)
