### ISSUE TITLE
Carbon CardView Shadow Does Not Appear in Pre Lollipop Devices

### ISSUE THREAD

**Issue by Jayvd** [ZieIony/Carbon#171]
I am using Carbon to create Shadow by using it's Elevation property

This `CardView` is used as `RecyclerView` `Item` view holder. In `Lollipop` devices, the shadow appears, but it doesn't in `Jellybean` devices.

    <carbon.widget.CardView
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:id="@+id/cardView"
        android:background="@color/WHITE_COLOR"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_centerInParent="true"
        app:carbon_colorBackground="@color/WHITE_COLOR"
        app:carbon_cornerRadius="@dimen/CORNER_RADIUS"
        app:carbon_elevation="3dp">

    </carbon.widget.CardView>

Anything I am missing here?

**Comment by ayalma** [comment]
You must use card with this syntax
carbon.widget.CardView

**Comment by Jayvd** [comment]
@ayalma Where should I put the Syntax? I did use `<carbon.widget.CardView/>`

**Comment by ayalma** [comment]
Sorry your last pm contains this carbonwidgetCardView so I send answer

**Comment by Jayvd** [comment]
Oh I see. Thanks for trying to help!

**Comment by ayalma** [comment]
are you using carbon.widget.RecyclerView  in your app?

**Comment by Jayvd** [comment]
No I didn't, should I? Is it related to the problem? 

Because on Lollipop the shadow exists.

**Comment by ayalma** [comment]
Yes you have to add , cuz in carbon some shadow depends on his parent view
and recycler view is parent of holder

**Comment by Jayvd** [comment]
Oh I see. Thank you. I'm gonna try it ASAP tomorrow. Thanks!

**Comment by ayalma** [comment]
You're welcome.

**Comment by Jayvd** [comment]
Just tried it. It works!!!!! Thank you man!!!!!!

**Comment by ayalma** [comment]
so you can close the issue.

**Comment by ZieIony** [comment]
Just to make clear, what is going on - shadow is always drawn by view's parent due to view clipping issues in Android. Each view only defines its shadow's properties, but is unable to draw it. That's why you always need both - a  Carbon layout and a Carbon child view to get the shadows working.

Thanks @ayalma for helping here :)

**Comment by Jayvd** [comment]
Is there any reason why on Lollipop devices the shadow appears regardless? Is it because carbon check the build version and simply set the elevation if it is Lollipop and above?

**Comment by ZieIony** [comment]
Yes, Carbon uses native solutions where possible. The carbon_elevation attribute is translated to elevation attribute on 5.+.
