### ISSUE TITLE
Add PercentRelativeLayout, PercentFrameLayout, PercentLinearLayout

### ISSUE THREAD

**Issue by reaper12** [ZieIony/Carbon#174]
I hope add PercentRelativeLayout, PercentFrameLayout, PercentLinearLayout

**Comment by ZieIony** [comment]
Could please add a new issue regarding borders for widgets? I feel like it's a separate issue. Could you elaborate on what you'd like to have?

**Comment by ZieIony** [comment]
I've just added two new issues (#175, #176). Could you please take a look and add descriptions to these issues?

**Comment by reaper12** [comment]
can you add these three widgets ?

**Comment by ZieIony** [comment]
I'm thinking about adding suport for percent dimensions to existing layouts. carbon.widget.FrameLayout and other layouts already support anchors and min/max size.

**Comment by ZieIony** [comment]
Percent sizes and margins are now supported by FlowLayout, FrameLayout, LinearLayout, RelativeLayout and GridLayout.
