### ISSUE TITLE
Switch

### ISSUE THREAD

**Issue by ZieIony** [ZieIony/Carbon#175]
Switch widget. See: https://www.google.com/design/spec/components/selection-controls.html#selection-controls-switch

**Comment by ZieIony** [comment]
Separated from #174

**Comment by ZieIony** [comment]
I'm not sure if adding Switch to Carbon is neccessary as there's SwitchCompat, which is pretty good and should work with Carbon without any changes. See: https://developer.android.com/reference/android/support/v7/widget/SwitchCompat.html

Let's keep this issue open for now.

**Comment by reaper12** [comment]
tks

**Comment by ZieIony** [comment]
Moved to the project
