### ISSUE TITLE
Borders for widgets

### ISSUE THREAD

**Issue by ZieIony** [ZieIony/Carbon#176]
Separated from #174.

@reaper12: "If widgets can set Border，it's perfect."

**Comment by ZieIony** [comment]
@reaper12: Could you please elaborate on what would you like to have?

**Comment by reaper12** [comment]
Button、TextView、EditView may be have,just like this
![11](https://cloud.githubusercontent.com/assets/13657190/12321424/e291241e-bae8-11e5-86e7-07b0b3a9e1eb.png)

**Comment by ZieIony** [comment]
Borders can be easily added using shapes and background drawable. See: http://stackoverflow.com/questions/6698927/border-in-shape-xml

That's why I don't think Carbon needs another mechanism for that. Also, borders have no use in Material Design.
