### ISSUE TITLE
Can you add clear button for EditText?

### ISSUE THREAD

**Issue by reaper12** [ZieIony/Carbon#177]
Can you add clear button for EditText?

**Comment by ZieIony** [comment]
Good idea, I thought about it.

**Comment by reaper12** [comment]
https://github.com/rengwuxian/MaterialEditText   This EditText is very good,Maybe you can see it

**Comment by ZieIony** [comment]
I know this library. MaterialEditText's clear buton doesn't have a ripple, doesn't support drawables, states and tinting. Click detection is also very simple. I would like to add something more complete to Carbon. It it's not possible, maybe the best option is to just create a layout with a button placed to the right of the text field.

**Comment by ZieIony** [comment]
done, see carbon.widget.InputLayout
