### ISSUE TITLE
Borderless Ripple not being rendered when setRippleDrawable is called Multiple Times

### ISSUE THREAD

**Issue by Teja-Konjeti** [ZieIony/Carbon#179]
The Borderless Ripple being rendered by your library for ImageButton (FloatingActionButton in your library) is much smaller than the ripple rendered by android system.

**Comment by ZieIony** [comment]
Could you add a screenshot? FloatingActionButton doesn't use borderless ripples and RippleDrawable is more or less a copy/paste from the official sources.

**Comment by Teja-Konjeti** [comment]
It is extending your ImageView which implements RippleView. So, I think it does..
Anyways I'll be uploading screenshots in a min!

**Comment by Teja-Konjeti** [comment]
Screenshots :
![screenshot_2016-01-15-17-33-01-01](https://cloud.githubusercontent.com/assets/12207194/12352699/76d169b6-bbae-11e5-8dc0-dc06aa68bbc6.jpeg)
![screenshot_2016-01-15-17-32-07-01](https://cloud.githubusercontent.com/assets/12207194/12352700/76d4216a-bbae-11e5-88fd-3939185ff2fe.jpeg)

**Comment by Teja-Konjeti** [comment]
1st: Carbon
2nd: Android
Thnx for d swift reply btw!

**Comment by Teja-Konjeti** [comment]
Oops! sorry I was using background style before
but now the problem is if I call setRippleDrawable Multiple times its not working. I'm not able to render any ripple just plain background. :/

**Comment by ZieIony** [comment]
FloatingActionButton uses background ripple cut to FAB's silhouette. ImageView's borderless ripple would be larger - its diameter should be equal to ImageView's diagonal. See:

```
<carbon.widget.ImageView
    style="@style/carbon_ImageView.Icon.Inverse"
    android:layout_width="@dimen/carbon_toolbarItemSize"
    android:layout_height="@dimen/carbon_toolbarItemSize"
    app:carbon_src="@raw/ic_airplanemode_on_24px" />

<carbon.widget.FloatingActionButton
    app:carbon_tint="?attr/carbon_iconColorInverse"
    android:layout_width="@dimen/carbon_toolbarItemSize"
    android:layout_height="@dimen/carbon_toolbarItemSize"
    android:background="@null"
    app:carbon_elevation="0dp"
    app:carbon_src="@raw/ic_airplanemode_on_24px" />
```

![ripple comparison](https://cloud.githubusercontent.com/assets/10180628/12352927/5e094fda-bb8a-11e5-8091-bb1e04c361d2.png)

**Comment by ZieIony** [comment]
Setting ripple multiple times is another story :)

I'll check that

**Comment by ZieIony** [comment]
Btw. you can use ImageView with style="@style/carbon_ImageView.Icon" to get nice clickable icons.

**Comment by Teja-Konjeti** [comment]
Ok! :)
Btw setting ripple Multiple times is working with background style
as in 

```
public void setRippleDrawable(RippleDrawable newRipple) {
    if (rippleDrawable != null) {
        rippleDrawable.setCallback(null);
        if (rippleDrawable.getStyle() == RippleDrawable.Style.Background)
            super.setBackgroundDrawable(rippleDrawable.getBackground() == null ? emptyBackground : rippleDrawable.getBackground());
    }

    if (newRipple != null) {
        newRipple.setCallback(this);
        if (newRipple.getStyle() == RippleDrawable.Style.Background) {
            super.setBackgroundDrawable((Drawable) newRipple);
        }
    }

    rippleDrawable = newRipple;
}
```

from your source

**Comment by Teja-Konjeti** [comment]
I would love to get this fixed as soon as possible!
I can be of any help if required!

**Comment by ZieIony** [comment]
To make it clear, using setRippleDrawable() with background ripple works. Using setRippleDrawable() with borderless ripple doesn't. Is that corrent?

**Comment by Teja-Konjeti** [comment]
Yep!

**Comment by Teja-Konjeti** [comment]
@ZieIony : Fixed it!!!
Pull Request on the Way! :)

**Comment by Teja-Konjeti** [comment]
@ZieIony : Check this out! https://github.com/ZieIony/Carbon/pull/180

**Comment by ZieIony** [comment]
Your pull request is looking good. I will review it asap. Thank you very much for your help!

**Comment by ZieIony** [comment]
Fixed

**Comment by Teja-Konjeti** [comment]
I'm getting the same issue on pre lollipop devices.
:/ was about to publish.. Plz fix it ASAP!
