### ISSUE TITLE
Does (beta) Dialog provide any benefit over AppCompat Dialog?

### ISSUE THREAD

**Issue by mvpmvh** [ZieIony/Carbon#18]
What is the purpose of your Dialog? It's just a Window holding a view, but not much other features come with this implementation. For whatever reason, when I select 'Ok', the UI freezes and the dialog does not disappear. Android already provides Dialogs in AppCompat21. Any reason why you wouldn't want to just use that directly (or extend it)?

**Comment by ZieIony** [comment]
You're right - my dialog is just a dummy window and I wouldn't recommend using it. I'm playing a bit with many things and windows are definitely one of them. Using AppCompat is a very good option and I'm thinking about using it as a base for what I would like to achieve.

I would like to provide three things, which are not working well in AppCompat:
- custom showing and hiding animations (See: http://www.google.com/design/spec/animation/responsive-interaction.html#responsive-interaction-material-response -> Point of origin)
- ripples for confirmation and action buttons
- consistent theming
