### ISSUE TITLE
toolbar class still extend the LinearLayout

### ISSUE THREAD

**Issue by ZieIony** [ZieIony/Carbon#181]
From #58:

@rhonyabdullah: "from the example project the Toolbar class extend v7.widget.Toolbar, but when i try to implement it into my project i see the toolbar class still extend the LinearLayout, what should i do ? 
try to rebuild still didn't work."

**Comment by ZieIony** [comment]
Toolbar class in the repository extends android.support.v7.widget.Toolbar correctly, so there might be an issue with your configuration. Which version are you using? Did you try to update?

See: https://github.com/ZieIony/Carbon/blob/master/carbon/src/main/java/carbon/widget/Toolbar.java

**Comment by rhonyabdullah** [comment]
Oh my mistake, upgrade to 0.12.0 fix the problem, thanks.
