### ISSUE TITLE
Spinner with floating label & error support?

### ISSUE THREAD

**Issue by ghost** [ZieIony/Carbon#186]

**Comment by ZieIony** [comment]
Could you please post an example of such widget? I've skipped these because I couldn't find any good appliance for them.

Spinner, TextView and EditText are all pretty much the same, so your request should be easy to implement. Maybe I should add label and error for TextView as well.

**Comment by ghost** [comment]
https://material.angularjs.org/latest/demo/select. Scroll to bottom for validation demo. If not a floating label, then the placeholder when no option is selected is fine. But If an option is selected, you would lose context of the dropdown.

**Comment by ZieIony** [comment]
Spinner now correctly extends EditText (technically it will in the upcoming commit). Underline, floating label, error, validation pattern and other stuff is turned off by default, but it's possible to turn them on just like it was an EditText.
