### ISSUE TITLE
Understanding Carbon Pattern & Widget Properties

### ISSUE THREAD

**Issue by rhonyabdullah** [ZieIony/Carbon#189]
Where can i learn about carbon pattern ? 
i got this `app:carbon_pattern="^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$"` pattern from the example but i don't understand what's that mean. Need some tutorial. 

And then how to find possibilities properties that can be used while using carbon widget ?

Thanks.

**Comment by ZieIony** [comment]
The carbon_pattern attribute accepts Java regular expressions. There's a lot of tutorials in the Internet. For example:
- https://docs.oracle.com/javase/tutorial/essential/regex/
- http://www.ocpsoft.org/opensource/guide-to-regular-expressions-in-java-part-1/

You can find widget reference on the wiki. It's probably not up to date, but you can start there. I'll try to find some time to update these docs. Here:
https://github.com/ZieIony/Carbon/wiki/Reference

**Comment by rhonyabdullah** [comment]
thanks, i'm gonna close this issue
