### ISSUE TITLE
FAB - Feature Request = Floating 

### ISSUE THREAD

**Issue by CrandellWS** [ZieIony/Carbon#196]
If you are interested in the bug skip to:

https://github.com/ZieIony/Carbon/issues/196#issuecomment-185241140 

Google has a sample for a Floating action button but:

  <h3>Pre-requisites</h3>

> Android SDK v21
> Android Build Tools v23.0.2
> Android Support Repository

Does not seem very usable or even easily portable.  Though I found another implementation of a FAB at https://github.com/EatHeat/FloatingExample 

The Class **FlyBitch** (could be renamed...) seems to be portable but I have not attempted this yet...additionally the styling does not have the CLEAN feel that would be desired, though that should be the easy enough to fix...

The invention is for me to work on this at some point but currently have other priorities. So no ETA on this from me.

Just want to exit with an open question.

What other ways might this be done?

**Comment by ZieIony** [comment]
It's known as a chat head, not a floating action button. This doesn't seem to be a Material Design feature, so I don't actually see a reason to add such thing to Carbon.

The implementation is based on a view added to WindowManager. You can add any view to WindowManager, including FloatingActionButton widget. The only difficulty is a proper window management, as leaving the window open after closing a parent activity may lead to memory leaks.

**Comment by CrandellWS** [comment]
thanks for the headsup on the memory leak, and yea you are right it is not Material Design...thank you for introducing the terminology "chat head". Was actually wondering what to call it...

I also agree with the variety of statements you made about what to and not to support. It is better to have reliability over new bugs.

On the other hand...perhaps a forked project could be called CarbonX as in Carbon with Extra...

Then with Carbon you get a well made library you can rely on, While CarbonX users get all the extra :bug:  features, and extra :bug: enhances.

**Comment by ZieIony** [comment]
The deal is that I don't have enough time to implement everything I would like. Thats why I have to reject some of ideas. I'm also trying to provide documentation and articles so everyone who wants to develop things using my code can do that.

**Comment by CrandellWS** [comment]
Stick to your guns, like I said I am impressed by your work, and grateful to be able to use it. I will help where and if I can...You say you need documentation....Well create a branch for that so I can provide pull requests, and I will try to document (javadoc) as I go about I could use the practice anyhow.

**Comment by ZieIony** [comment]
Documentation is on wiki. You can add and edit pages there, if you wish. I don't like javdocs, because Carbon has tons of duplicated code and javadocs could increase duplication even more.

**Comment by CrandellWS** [comment]
Honestly, I would prefer write javadocs than wiki pages...but I will look and see what I can do on the wiki.

I did notice the extra code duplication...and was thinking about how to fix that...I will see if I can figure anything I can do to help out there...but it may be a week or more before I come back to this.

Uh, it does not change how I feel but I did find a bug in the demo...on the DesignActivity.java page when you click the back button on the screen in the top left corner...get a cast type error...

leads me to Toolbar.java:89...

```
    icon.setOnClickListener(new OnClickListener() {
        @Override
        public void onClick(View v) {
            ((Activity) getContext()).onBackPressed();
        }
    });
```

and I found this http://stackoverflow.com/a/27434704/1815624 ...

**Comment by CrandellWS** [comment]
yelp that worked Toolbar.java

```

    private static Activity scanForActivity(Context cont) {
        if (cont == null)
            return null;
        else if (cont instanceof Activity)
            return (Activity)cont;
        else if (cont instanceof ContextWrapper)
            return scanForActivity(((ContextWrapper)cont).getBaseContext());

        return null;
    }
```

```
    icon.setOnClickListener(new OnClickListener() {
        @Override
        public void onClick(View v) {
            scanForActivity(getContext()).onBackPressed();
        }
    });
```

**Comment by ZieIony** [comment]
Always open a new issue for each topic. Renaming and adding new topics to existing issues makes problems and solutions hard to find for others.

See: #197

**Comment by CrandellWS** [comment]
will do.
