### ISSUE TITLE
Back button in DesignActivity throws exception

### ISSUE THREAD

**Issue by ZieIony** [ZieIony/Carbon#197]
extracted from #196 

@CrandellWS: on the DesignActivity.java page when you click the back button on the screen in the top left corner...get a cast type error...

leads me to Toolbar.java:89...

```
    icon.setOnClickListener(new OnClickListener() {
        @Override
        public void onClick(View v) {
            ((Activity) getContext()).onBackPressed();
        }
    });
```

and I found this http://stackoverflow.com/a/27434704/1815624 ...

**Comment by CrandellWS** [comment]
bug fix diff 
https://github.com/CrandellWS/Carbon/commit/f65a2e573f24c30661575cc7856ff323795b40dd#diff-8f27c5d783578944c7bf901400ab72ae

**Comment by ZieIony** [comment]
Thanks! Fixed

**Comment by CrandellWS** [comment]
no @ZieIony thank you for your current updates you have solved an unmentioned issue and saved me the time. Thank you.
