### ISSUE TITLE
RadialTransition

### ISSUE THREAD

**Issue by kegita** [ZieIony/Carbon#2]
Hi! Radial Transition is a sort of Custom Activity? and if i would like use it, i have to insert fragments inside it??? Thanks

**Comment by ZieIony** [comment]
Hello.
Radial transition is one of the effects of TransitionLayout. It's a kind of a ViewFlipper, so it uses views. You have to add two views to the TransitionLayout instance and call startTransition.

**Comment by kegita** [comment]
I have looked at your example and i have seen that you use 3 pl.zielony.carbon.widget.LinearLayout and switch between them with a button. So, inside TransitionLayout, i can't insert fragments but only pl.zielony.carbon.widget.LinearLayout,true??

**Comment by ZieIony** [comment]
You can add any View there, not only pl.zielony.carbon.widget.LinearLayout. Adding fragments is also pretty simple. You just have to add a container to the TransitionLayout instance and add your fragment to the container. See the updated sample I just commited.

**Comment by kegita** [comment]
Ok,thanks a lot!
