### ISSUE TITLE
RenderScript problems.

### ISSUE THREAD

**Issue by HectorFGarcia** [ZieIony/Carbon#200]
When I load a fragment I'm getting this. This log appears on a 4.0.3 device. 

```
 02-19 12:46:06.859 32243-32243/com.otx.gpi E/RenderScript_jni: No GC methods
 02-19 12:46:06.867 32243-32243/com.otx.gpi D/dalvikvm: Trying to load lib /data/data/com.otx.gpi/lib/librsjni.so 0x41329fc8
 02-19 12:46:06.867 32243-32243/com.otx.gpi D/dalvikvm: Added shared lib /data/data/com.otx.gpi/lib/librsjni.so 0x41329fc8
 02-19 12:46:06.867 32243-32243/com.otx.gpi V/RenderScript_jni: RS compat mode
 02-19 12:46:06.875 32243-32243/com.otx.gpi D/dalvikvm: Trying to load lib /data/data/com.otx.gpi/lib/libRSSupport.so 0x41329fc8
 02-19 12:46:06.890 32243-32243/com.otx.gpi D/dalvikvm: Added shared lib /data/data/com.otx.gpi/lib/libRSSupport.so 0x41329fc8
 02-19 12:46:06.890 32243-32243/com.otx.gpi D/dalvikvm: No JNI_OnLoad found in /data/data/com.otx.gpi/lib/libRSSupport.so 0x41329fc8, skipping init
 02-19 12:46:06.890 32243-32243/com.otx.gpi V/RenderScript_jni: Unable to load libRSSupportIO.so, USAGE_IO not supported
 02-19 12:46:06.890 32243-32447/com.otx.gpi E/RenderScript: Couldn't load libRSSupportIO.so
```

The problem is that when this error is happening, all threads running goes slow down, they need two o three times the usual time to finish. It's probably beacause the device has a poor hardware and can't handle the load and the threads running at the same time. So I really need to fix that failing load somehow.

P.S. I'm really really sorry about having bizarre problems all the time. I'm developing a "big industrial app" so I'm using your library a lot over unusual Android devices.

**Comment by ZieIony** [comment]
The only thing that comes to my mind is to turn OpenGL off for slower devices. Carbon can run in software mode, which is supposed to run on all devices.

https://github.com/ZieIony/Carbon/blob/master/carbon/src/main/java/carbon/shadow/ShadowGenerator.java#L23

This setting is not exposed, because it was only used as a fallback, not as a primary mode.

Or maybe this is your issue - Carbon is switching to software mode and that's why it's running slower than usually.

**Comment by HectorFGarcia** [comment]
Check this: https://github.com/wasabeef/Blurry/issues/16

I downgraded to build tools 22.0.1 and 21.1.2 and now the library works again.

**Comment by ZieIony** [comment]
Nice finding! I'm working with good numer of devices as well and never experienced your issue. Let's keep this issue open. I'll try to find a device with your exception and make software mode work for it.

**Comment by HectorFGarcia** [comment]
This happens on a Honeywell Dolphin E70. SoC is a TI OMAP (v3 I think, I couldn't find it) and CPU is a Cortex-A8 1Ghz singlecore.

Happy to help :)

**Comment by ZieIony** [comment]
I've never experienced this issue, despite testing on wide variety of devices. I haven't seen the phone you mentioned and I didn't get any other related bug reports. I hope that either build tools or something in Carbon itself fixed it. I've added a try - catch to RenderScript code long time ago, but I'm not sure if it helped.
