### ISSUE TITLE
if I use the linearLayout and button ,it will crash!

### ISSUE THREAD

**Issue by ray0807** [ZieIony/Carbon#202]
![image](https://cloud.githubusercontent.com/assets/7233544/13449200/2b31dc2c-e064-11e5-8bb4-1778b121a6cc.png)

But  in your samples, it's OK!
I don't know why.

**Comment by ZieIony** [comment]
Did you go through the installation page? Make sure that:
- you have RenderScript configured correctly
- you're using one of Carbon's themes
- you're using one version of Carbon in all modules. Don't add support libraries - Carbon has correct ones inside.

You can find the installation guide here:
https://github.com/ZieIony/Carbon/wiki/Installation

**Comment by ZieIony** [comment]
7 days without an answer - I assume that it's working. Closing.
