### ISSUE TITLE
Borderless Ripple not being rendered when setRippleDrawable is called Multiple Times

### ISSUE THREAD

**Issue by Teja-Konjeti** [ZieIony/Carbon#203]
This is the same problem as #179 this issue still persists on pre - lollipop devices.

**Comment by ZieIony** [comment]
I'm investigating your issue on Gingerbread. I've modified ListRippleActivity/ListRippleAdapter sample with the following code:

```
    @Override
    public void onBindViewHolder(ListRippleAdapter.ViewHolder holder, final int position) {
        ((LinearLayout)holder.itemView).setRippleDrawable(new RippleDrawableFroyo(ColorStateList.valueOf(0x42ff0000),null, RippleDrawable.Style.Borderless));
        ((LinearLayout)holder.itemView).setRippleDrawable(new RippleDrawableFroyo(ColorStateList.valueOf(0x42ff0000),null, RippleDrawable.Style.Borderless));
        holder.textView.setText(items[position]);
    }
```

Borderless ripples work fine in this case. Could you provide an example you're experiencing issues with?

**Comment by Teja-Konjeti** [comment]
I call the method dynamically with different colors as mentioned in #179 . The Fix I suggested is working for Lollipop and above. I didn't check it back then on pre - lollipop devices.

**Comment by Teja-Konjeti** [comment]
@zielony Did u fix it?

**Comment by ZieIony** [comment]
No. The case you described works for me no problem. I'm unable to reproduce the issue

**Comment by ZieIony** [comment]
No answer for more than 7 days, I'm unable to reproduce the issue - closing.
