### ISSUE TITLE
Library is massive - Split into smaller libraries?

### ISSUE THREAD

**Issue by tomblenz** [ZieIony/Carbon#206]
I included this library in my project and the minified project size went from 3mb to 6mb.  I turned on shrinkResources and it is still at 5.2mb.

My use of the library is limited to its CardView - perhaps the library could be split into a core library + feature libraries?

**Comment by ZieIony** [comment]
No, this is not really possible.

Carbon includes support libraries, which add a lot of methods and bytes. Shadows drawn by Carbon are using RenderScript, which is another heavy thing which cannot be removed. SVG graphics and carbon.\* classes are small, so removing them won't change that much.

Splitting vertically is not an option as well. Carbon's components are tightly integrated with each other. Shadows, ripples, attributes, graphics, layouts, animations - all of these are used in almost each widget and cannot be extracted.

The only reasonable way is to use ProGuard and cut unused classes out.
