### ISSUE TITLE
I hope perfect the Percent for RelativeLayout,FrameLayout, LinearLayout like this

### ISSUE THREAD

**Issue by reaper12** [ZieIony/Carbon#218]
like this:https://github.com/hongyangAndroid/android-percent-support-extend

**Comment by ZieIony** [comment]
Carbon already supports percent size width, height, margin and aspectRatio - all common layout parameters. Just like the official percent layouts.

General support for percent values (textSize, alpha, touchMargin, etc.) is tempting, but adds complexity, large number of attributes and methods. I don't think that it's really needed - Android rather focuses on densities and relative layouts than simple scalling. Specific cases should be handled using custom classes.
