### ISSUE TITLE
The CheckBox is not in the center of ripple.

### ISSUE THREAD

**Issue by AI888Wealth** [ZieIony/Carbon#219]

**Comment by ZieIony** [comment]
Could you please add more details? CheckBox's drawable can be adjusted using padding.

**Comment by AI888Wealth** [comment]
![2016-03-25 6 35 18](https://cloud.githubusercontent.com/assets/8340605/14042803/72aaf0dc-f2b8-11e5-96ea-6775da39bcd4.png)
![2016-03-25 6 34 37](https://cloud.githubusercontent.com/assets/8340605/14042804/73f5b238-f2b8-11e5-9312-4971b1c91d5d.png)

**Comment by AI888Wealth** [comment]
![2016-03-25 6 39 06](https://cloud.githubusercontent.com/assets/8340605/14042874/04b66a92-f2b9-11e5-858f-74e4c1025418.png)
The right text of CheckBox maybe displays wrong.

**Comment by AI888Wealth** [comment]
<carbon.widget.CheckBox
        android:id="@+id/checkBox"
        android:layout_width="48dp"
        android:layout_height="48dp"
        android:layout_gravity="end"
        android:gravity="center_vertical"
        android:paddingLeft="12dp"
        android:text="check me!"
        app:carbon_rippleColor="?attr/carbon_rippleColor"
        app:carbon_rippleHotspot="false"
        app:carbon_rippleStyle="borderless"/>

**Comment by ZieIony** [comment]
This issue has its root in android.widget.CheckBox & RadioButton. I rewrote those along with CheckedTextView, RadioGroup, listeners and styles. It's working as expected now.
