### ISSUE TITLE
The Circular progress is not good in android 4.4.

### ISSUE THREAD

**Issue by AI888Wealth** [ZieIony/Carbon#220]
![2016-03-25 11 05 46](https://cloud.githubusercontent.com/assets/8340605/14037011/22e70966-f27a-11e5-8574-a66c8b8df6b2.png)

**Comment by ZieIony** [comment]
Fixed as suggested by one of users (by insetting arc's bounds by a tiny amount). I don't know what is the real issue though. The arc is clipped to view's bounds, so it should be fine. Maybe it's a bug in Android?
