### ISSUE TITLE
No resource identifier found for attribute 'carbon_menu' in package 'com.z3r0byte.magi'

### ISSUE THREAD

**Issue by Z3r0byte** [ZieIony/Carbon#225]
Hey,

When i try to use a actionbuttonmenu in my app I get the following error:
`Error:(19) No resource identifier found for attribute 'carbon_menu' in package 'com.z3r0byte.magi'`
Is there a way to solve this? I am using version 0.11.0.

Thanks in advance,

Z3r0byte

**Comment by ZieIony** [comment]
This attribute was introduced in 0.12.0
