### ISSUE TITLE
Render Script Problem

### ISSUE THREAD

**Issue by Teja-Konjeti** [ZieIony/Carbon#232]
I got this crash report from a user ![screenshot_2016-04-07-15-31-43](https://cloud.githubusercontent.com/assets/12207194/14347760/6081aa90-fcd6-11e5-9c4e-a064c3cd899e.png)

**Comment by ZieIony** [comment]
Do you have any more information (device and system are the most interesting). I'm thinking about preparing Carbon version for devices without RenderScript.

**Comment by Teja-Konjeti** [comment]
Asus Zenfone 5 running API 19

**Comment by Teja-Konjeti** [comment]
The Device uses x86 Architecture I think that's the problem

**Comment by Teja-Konjeti** [comment]
I know an app named poweramp which releases different versions of their app for different architectures

**Comment by ZieIony** [comment]
Are you, by any chance, using ProGuard? This error looks like that method was removed by ProGuard rule as unused. I tested Carbon on ASUS Zenfone with x86 CPU and it was 100% fine.

**Comment by Teja-Konjeti** [comment]
Yes, I use proguard in the release. I thought your library supports it as I didn't find anything in the installation documentation.

**Comment by ZieIony** [comment]
I should probably add a note to the installation guide. Carbon works well with ProGuard, but you have to add a rule to keep RenderScript. Samples app uses that. See: https://github.com/ZieIony/Carbon/issues/172

**Comment by ZieIony** [comment]
Added to https://github.com/ZieIony/Carbon/wiki/Installation
