### ISSUE TITLE
ImageView broken when creating from code

### ISSUE THREAD

**Issue by NeverGivinUp** [ZieIony/Carbon#238]
In Version 0.12.0 of Carbon, the initImage method is conditional on attrs != null. This leaves some variables uninitialized. The variables inAnim being uninitialized causes a nullpointer exception when changing visibility (method setVisibility calles AnimUtils.animateIn() with a null reference)

**Comment by ZieIony** [comment]
inAnim is set to AnimUtils.Style.None since 8da69d0b8483a3a63bc57df5d25edf3e5c5e4ad2

I'm working on releasing version 0.13.0 soon. That should help
