### ISSUE TITLE
The layout of FlowLayout & Chips has some problem.

### ISSUE THREAD

**Issue by AI888Wealth** [ZieIony/Carbon#244]
As shown below:
![device-2016-06-27-105822](https://cloud.githubusercontent.com/assets/8340605/16367498/99b246ca-3c56-11e6-8cfd-26e95f9ab0d9.png)

**Comment by ZieIony** [comment]
You seem to be using RTL layouts. Am I right?

What version of Android are you using?

**Comment by AI888Wealth** [comment]
I didn't modify any code.The version of Android is 5.1.1.

**Comment by ZieIony** [comment]
fixed
