### ISSUE TITLE
How to achieve this effect

### ISSUE THREAD

**Issue by reaper12** [ZieIony/Carbon#249]
![aa](https://cloud.githubusercontent.com/assets/13657190/16828810/c497f0f2-49c5-11e6-87c5-f7989e6944d5.png)

**Comment by ZieIony** [comment]
You mean the ripple? You can use 'style="@style/carbon_ImageView.Icon"' on an ImageView. That's one of the possibilities. You can also use 'carbon_rippleColor' and 'carbon_rippleStyle' attributes. Another way is to create RippleDrawable from code and set it as a background.

Just remember to make the view clickable.

**Comment by reaper12** [comment]
I mean the ripple' s Angle . I used carbon_cornerRadius,but the result is bad

**Comment by ZieIony** [comment]
This kind if ripple is called 'borderless'. Just set 'carbon_rippleStyle="borderless"'

**Comment by reaper12** [comment]
How to cover to top and bottom part?

**Comment by reaper12** [comment]
I got it. tks
