### ISSUE TITLE
Remove CardView

### ISSUE THREAD

**Issue by ZieIony** [ZieIony/Carbon#251]
CardView is just a RelativeLayout with a special style. Any layout can be styled this way. CardView class hides the true layout and adds one more level of calls.

**Comment by ZieIony** [comment]
Marked as Deprecated for now

**Comment by tuckercr** [comment]
The wiki doesn't state that CardView was removed/deprecated
https://github.com/ZieIony/Carbon/wiki/CardView

**Comment by ZieIony** [comment]
Wiki is very outdated in general. Carbon changes two times a week and usually I forget to update the Wiki. The sample app is a much better place to look for API answers.

If I recall correctly, users can introduce changes to the Wiki. If you wish to help, you're welcome to update pages. I'll try to make it more up to date as well.
