### ISSUE TITLE
Seekbar floating label issue

### ISSUE THREAD

**Issue by ishowrunes** [ZieIony/Carbon#257]
When using seekbar inside a dialog, the floating is drawn outside of the dialog.

**Comment by ZieIony** [comment]
That would be the correct behavior - floating label is displayed in a popup and it always floats over any UI. If I understood wrong, please elaborate and post a screenshot if possible.

**Comment by ishowrunes** [comment]
[Here](http://i.imgur.com/8bKrvz0.png). I have attached the image. The floating label is outside of the dialog.

**Comment by ZieIony** [comment]
I thought it was slightly out of the dialog. It's a bug then.

**Comment by ZieIony** [comment]
Fixed. The latest version can be obtained only by cloning the repository. There's no release yet since I'm working on something.
