### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by eladbitton** [ZieIony/Carbon#258]
I am trying to use this library in my android app, but when i am trying to sync the gradle file this happens:
Error:(8, 13) Failed to resolve: com.android.support:gridlayout-v7:23.1.1
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:*">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

This is only because of this library because when I'm removing its dependency isn't happening anymore.

Android studio suggest me to "Install Repository and sync project" but it doesn't work. Any way i can fix this?

**Comment by ZieIony** [comment]
Do you have support repositories installed? You can do that manually from the SDK Manager.

**Comment by eladbitton** [comment]
Support repository is installed, but still can't run the project.

![2016-11-22 20_23_52-start](https://cloud.githubusercontent.com/assets/15705362/20536423/ab137514-b0f1-11e6-8d39-005e6cc595c0.png)
![2016-11-22 20_24_20-cortana](https://cloud.githubusercontent.com/assets/15705362/20536424/ab1432a6-b0f1-11e6-80f9-b72f8d004d73.png)

**Comment by ZieIony** [comment]
It's most likely an issue with your environment configuration and there's not much I can do to help you. If you get stuck, while sure that it's gridlayout only, you can clone the repository, remove the dependency and import the library without gridlayout.
