### ISSUE TITLE
The Button set android:background no changed on Android 6.0

### ISSUE THREAD

**Issue by reaper12** [ZieIony/Carbon#260]
The Button set android:background no changed on Android 6.0

**Comment by ZieIony** [comment]
Could you please elaborate on your issue? Or prepare a short example with expected and your result

**Comment by ZieIony** [comment]
I tried to reproduce your issue, but with no luck. Without detailed issue description I'm unable to help you.

**Comment by ZieIony** [comment]
Finally I noticed your issue, while working on something else. It's fixed now.
