### ISSUE TITLE
Child items disappear on ExpandableRecyclerView scroll

### ISSUE THREAD

**Issue by NamtarR** [ZieIony/Carbon#261]
Hello! 
There is a bug in ExpandableRecyclerView. Can't figure out myself how to fix this. Somehow these child views alpha is 0.
Steps to reproduce (Carbon samples app will do):

1. Scroll to top.
2. Expand first, second and third groups.
3. Scroll to the very bottom to hide some of child views.
4. Collaps the third group to make it automatically scroll from top
5. Scroll back to the very top

Expected results:
All child views are visible.

Actual results:
Some child views are invisible. They are still clickable but invisible.

![img_2017-01-12 14 25 27](https://cloud.githubusercontent.com/assets/16237530/21880708/fce831c8-d8d2-11e6-8db2-1738c9bebabc.jpg)

**Comment by ZieIony** [comment]
fixed
