### ISSUE TITLE
 error: cannot find symbol class TransitionLayout

### ISSUE THREAD

**Issue by c4adarsh** [ZieIony/Carbon#262]
I think TransitionLayout.java file is not checked in.
import carbon.beta.TransitionLayout  is in PowerMenuActivity.

**Comment by ZieIony** [comment]
TransitionLayout was removed in favor of circular reveal. I plan to rewrite power menu using that.

**Comment by c4adarsh** [comment]
I was trying to compile the code but it doesn't. Anyways no problem. I will try to compile once your repository is in stable state to compile.

**Comment by ZieIony** [comment]
Now this is a nice finding. I thought you meant the layout, beacuse I'm working on samples and it's fine for me.

Apparently my Android Studio still has that class in cache. I've removed all references to TransitionLayout, so it should compile now. The affected samples are not really working though.
