### ISSUE TITLE
Spinner dropdown style

### ISSUE THREAD

**Issue by Droppers** [ZieIony/Carbon#265]
Is there a way to disable the scrolling and let it really act like a dropdown menu? Images explain the 'issue' I'm having.

Example, when nothing is selected:
![](http://i.imgur.com/vMXS3wA.png)

When 'Three' is selected:
![](http://i.imgur.com/UCV1fru.png)

**Comment by ZieIony** [comment]
No, there's no way. I think that there should be an option though.

**Comment by ZieIony** [comment]
Done. To change menu's mode, specify `app:carbon_mode="fit|over"` for DropDown in xml. `fit` tries to fit entire menu on screen while `over` places selected item on top of the DropDown.
