### ISSUE TITLE
update samples

### ISSUE THREAD

**Issue by ZieIony** [ZieIony/Carbon#269]
- [x] remove List ripple sample
- [x] EditText in Auto Complete should have white background
- [x] remove Toolbars / Usage
- [x] black button in Buttons should have light text
- [x] Image fade should fade to alpha, now fades to black. More images
- [x] Snackbar needs a toolbar
- [x] Shadow needs a toolbar
- [x] Large shadow needs a toolbar
- [x] Colors should show selected colors
- [x] CheckBoxes & RadioButtons needs a toolbar, buttons at the bottom should have shadow, cleanup check boxes and radios
- [x] padding in Percent layout should be moved outside so the views take exactly 25%/50%
- [x] DropDown shouldn't have colored arrows
- [x] Registration form hides floating labels on start
- [x] check shadow animation in Widget animations
 - [x] Calculator crashes
 - [x] RecyclerView & cards has black, sharp corners
 - [ ] Make header scroll with drawer in Navigation drawer. Nicer menu
 - [x] Design Support Library looks bad
  - [x] Icon and text list item needs better data
  - [x] Power Menu doesn't work
  - [x] Quick Return needs nicer data, a title and more data to make the FAB hide
 - [x] Dependency layout doesn't pass events
 - [x] Text marker sample needs a toolbar, more explanation and a better example
 - [x] Theme sample doesn't work
 - [x] Buttons / Usage uses wrong colors, top icon is not aligned, buttons are cut
 - [x] progress demos need toolbars
 - [x] add toolbars, titles and descriptions

**Comment by galibimtiaz** [comment]
It would be nice if you add the APK of the sample. Its kinda pain if anyone wants to test it for the 1st time.

**Comment by ZieIony** [comment]
Moved to projects
