### ISSUE TITLE
InputLayout dose not align to center.

### ISSUE THREAD

**Issue by galibimtiaz** [ZieIony/Carbon#271]
Usual InputLayout dose get affected by gravity="center_horizontal",
But carbon.widget.InputLayout dose not. Is there any way I can align my floating label to center ?

**Comment by ZieIony** [comment]
No, there's no way. At least for now. I'm marking this issue as enchancement.

**Comment by ZieIony** [comment]
I tried to reproduce the behaviour you mentioned, but with no luck. Nevertheless, I've added support for android:gravity for InputLayout.
