### ISSUE TITLE
InputLayout is extremly hard to control in ConstraintLayout.

### ISSUE THREAD

**Issue by galibimtiaz** [ZieIony/Carbon#274]
I was working with ConstraintLayout and I put InputLayout  with edittext , as a result everything got messed up , I could not control the InputLayout is was almost impossible to move when edittext inside it, every time I tried to position the inputlayout, edittext gets separated.

What I did was I put that InputLayout inside a framelayout and that gave a handle to move freely in ConstraintLayout.

**Comment by ZieIony** [comment]
I tried to reproduce your issue several times, but unfortunatelly ConstraintLayout is not working for me inside the editor (all I can see is a gray rectangle). I suppose that it's about the Canary AS. Inside other layouts InputLayout works fine for me.

**Comment by galibimtiaz** [comment]
Well it did not worked for me either , thats why I made this issue, I manually put the strings with the code to position my my layouts , Editor prevent me from moving objects freely. But using framelayout as a parent layout of input layout showed me the current position more clearly which did not showed before.

**Comment by ZieIony** [comment]
![image](https://user-images.githubusercontent.com/10180628/28238984-9d9c9b86-6960-11e7-9d6f-4b419bdead69.png)

This is pretty much all I can see in the editor. Apparently it's a bug in either Goolge's support lib or the editor.

**Comment by galibimtiaz** [comment]
Same here, but last time it at least showed the items on the edges but now noting.

**Comment by ZieIony** [comment]
The editor is working, so I played a little with ConstraintLayout and InputLayout today. On Android Studio 3.0 beta 2 with current Carbon sources it's working fine for me. I'm not happy with how some of Carbon widgets look in the preview, but that's another story.

![image](https://user-images.githubusercontent.com/10180628/29294309-07b2317e-814f-11e7-82ff-6f1a7465ee01.png)
