### ISSUE TITLE
InputLayout dose not clear error when EditText is blank.

### ISSUE THREAD

**Issue by galibimtiaz** [ZieIony/Carbon#275]
I am using the code from the sample to an email and password field , when I type something it pops up error but when I clear the filed and even when I focus to the next object, InputLayout keep showing the error unless I type an email.

**Comment by galibimtiaz** [comment]
and also carbon_label disappears when field is not focused anymore (when the edittext is not blank).

**Comment by ZieIony** [comment]
Label automatically disappears when it's set to floating style. Use `app:carbon_labelStyle="persistent"` to get a persistent label.

Empty email is not valid, so the behavior is correct. InputLayout clears error state only if the text matches the set pattern.

**Comment by galibimtiaz** [comment]
`app:carbon_labelStyle="persistent"` put the label to the top always. What if I want to make my label style floating by default and only when edittext is not empty it will change to persistent style ?

**Comment by ZieIony** [comment]
I've added new style called `ifNotEmpty` which does exactly what you suggested. I'm not sure if the name is the best, but it should do the job :)
