### ISSUE TITLE
Percent layout crashes.

### ISSUE THREAD

**Issue by galibimtiaz** [ZieIony/Carbon#277]
I was trying the percent layout demo and it crash every time.

**Comment by ZieIony** [comment]
Could you provide a stacktrace?

Are you, by any chance, using the compiled sample app downloaded from Dropbox? If so, please redownload - there was an issue with percent layout and it was fixed. I've uploaded the most recent apk just now.

**Comment by galibimtiaz** [comment]
Ah sorry , Seems like its fixed now , I was using apk from drop box , I just downloaded the latest one and it seems fine now.
