### ISSUE TITLE
Light Theme issue with third-party views

### ISSUE THREAD

**Issue by tronghieubk** [ZieIony/Carbon#28]
Currently theme carbon_Theme.AppCompat.Light extend theme Theme.AppCompat and override the styles of almost views, so it's OK to use these views in Light Theme. But when I use some third-party views, it's defaulted with Dark Theme of Theme.AppCompat (all text colors are in white). 

My current workaround is to create a new theme, copy theme styles from values.xml and extends Theme.AppCompat.Light instead of Theme.AppCompat. It would be nicer if the lib can handle these third-party view.

**Comment by ZieIony** [comment]
All Carbon themes extend right android and AppCompat themes now:

"carbon_Theme.Dark" extends "android:Theme.NoTitleBar"
"carbon_Theme.Light" extends "android:Theme.Light.NoTitleBar"

**Comment by tronghieubk** [comment]
Thank you :+1:

**Comment by ZieIony** [comment]
I'm going to remap AppCompat theme colors to Carbon theme colors soon. For now the change should be sufficient.

**Comment by tronghieubk** [comment]
Can I ask is it possible to add a function to set text to carbon.widget.Button without capitalizing it? I want to extend it and apply Font Awesome icon to it using Iconify, but setText() in carbon.widget.Button auto capitalize it.

**Comment by ZieIony** [comment]
The method is there. It's called setAllCaps. There's also an attribute carbon_textAllCaps. You can also set a transformation method manually. Check the sources in case of any troubles.

```
public void setAllCaps(boolean allCaps) {
    if (allCaps) {
        setTransformationMethod(new AllCapsTransformationMethod(getContext()));
    } else {
        setTransformationMethod(null);
    }
}
```
