### ISSUE TITLE
android studio build error

### ISSUE THREAD

**Issue by ghost** [ZieIony/Carbon#280]
Error:(43, 27) No resource type specified (at 'text' with value '@{data.text}').
Error:(24, 26) No resource type specified (at 'src' with value '@{data.getAvatar(context)}'). 
android studio build error

**Comment by galibimtiaz** [comment]
Add data binding support in gradle.

```
android {
    ...

   dataBinding {
        enabled = true
    }
}
```

**Comment by ZieIony** [comment]
I'll add that to the installation instructions
