### ISSUE TITLE
EditText on focus change prevent InputLayout to show carbon_label

### ISSUE THREAD

**Issue by galibimtiaz** [ZieIony/Carbon#282]
Setting up on focus change listener to carbon edittext is preventing input layout to show label.

**Comment by ZieIony** [comment]
That's right. Focus change listener is used by InputLayout to determine if the view is focused. I'm not sure what would be the right way to support your situation. I don't want to add another listener to EditText as in general case any widget could be used as a source of input.

**Comment by ZieIony** [comment]
It's possible to use propagated drawable state change instead of focus change listener. That should be less destructive.

**Comment by galibimtiaz** [comment]
Can you give me an example ?
What I am trying to do is clear input text error when user click or focus on the edittext.

**Comment by ZieIony** [comment]
It's something I have to add to Carbon

```
    @Override
    protected void drawableStateChanged() {
        if (inDrawableStateChanged)
            return;

        inDrawableStateChanged = true;
        super.drawableStateChanged();
        updateHint(child);
        inDrawableStateChanged = false;
    }
```

**Comment by ZieIony** [comment]
fixed

**Comment by galibimtiaz** [comment]
just tested with the new update , that bug is still there.

**Comment by ZieIony** [comment]
I just added a focus listener to the text fields sample and the label is shown properly. The code:

```
EditText editText = (EditText) findViewById(R.id.editText);
editText.setOnFocusChangeListener((v, hasFocus) -> editText.setText(""));
```

Are you sure that you're using the most recent version? If the issue persists, maybe I'm testing it inproperly. In such case, could you prepare a minimal project showing the issue?

**Comment by galibimtiaz** [comment]
Ok I will check it again now.

**Comment by galibimtiaz** [comment]
Nah it was my mistake , library seems just fine, maybe I did not imported the latest update properly. I am sorry.
