### ISSUE TITLE
Any plan for adding viewpager Indicator ?

### ISSUE THREAD

**Issue by galibimtiaz** [ZieIony/Carbon#283]
It would be cool to have one.

**Comment by ZieIony** [comment]
Any example? I don't remember any MD specific ViewPagerIndicator widget.

There's a ton of ViewPagerIndicator libraries, so it's somewhere at the end of my list.

**Comment by galibimtiaz** [comment]
Actually I was looking for a circular viewpager indicator, I know there's tons of them thats what made them more confusing, I saw many of them highly customizable and some that are very simple but some features are missing like animation sycn with the drag etc.

I like JakeWharton's ViewPagerIndicator, its awesome but its not maintained anymore. So I thought maybe carbon can has its own viewpager indicator that is simple and customizable but not too complex.

**Comment by ZieIony** [comment]
I've just added a very simple ViewPagerIndicator widget. For now it can only display circles whose color can be controlled with `carbon_tint` attribute. And the animation code could be better.

![image](https://cloud.githubusercontent.com/assets/10180628/25066662/ff25567a-222c-11e7-8c93-fc9dee3ad619.png)
