### ISSUE TITLE
Changing component theme color.

### ISSUE THREAD

**Issue by galibimtiaz** [ZieIony/Carbon#284]
For example my primary color is blue, so my usual components will be tinted blue as well.
But what if I want my specific components color to red ? 

I am not just talking about background color , user can change that components primary and accent color.

Is there any way to change it ?

**Comment by ZieIony** [comment]
Sure.

Each widget has its colors customizable from xml and from code. Each widget is different, so I'm unable to answer your question in a more detailed way. Explore the sample app and try to find attributes you need.

You can use `carbon_tint`/`carbon_tintMode` and `carbon_backgroundTint`/`carbon_backgroundTintMode` to customize tinting, just like using Lollipop's API. It's widget-specific, so you have to take a look at styles.xml to find out what's possible. If a color is set to `#00000000`, that color is replaced with a default state list created from code.

Each widget (I guess) has its corresponding style you can customize and set in theme.

If you wish to alter the theme per widget, you can set `carbon_theme` per widget in xml. Just like in feature/theme sample.
