### ISSUE TITLE
No resource identifier found for attribute 'carbon_elevationShadowColor' in package

### ISSUE THREAD

**Issue by hippyk** [ZieIony/Carbon#297]

**Comment by ZieIony** [comment]
Could you please elaborate? What are the steps to reproduce? Which version are you using? Did you try to compile the most recent commit?

**Comment by hippyk** [comment]
I used this in as： compile 'tk.zielony:carbon:0.14.0'

**Comment by ZieIony** [comment]
0.14.0 didn't have colored shadows yet. It's a recent feature and there's no release with it yet. If you wish to use colored shadows now, you can download the repo and import it to your project locally.

**Comment by toXel** [comment]
@ZieIony Will there be a release with this feature anytime soon? Would be very nice :)

**Comment by ZieIony** [comment]
The deal with the upcomming release is that it's using canary tools from Google. I'm waiting for data binding 3.0, lambda support and aar support to become stable. That's why the release date is unknown even to me.

**Comment by toXel** [comment]
@ZieIony Ok I see... Any other idea how I can achieve colored shadows on a CardView? Or maybe you could make a prerelease?

_Sent from my HTC 10 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ZieIony** [comment]
Colored shadows are not supported by Lollipop nor the Support Library. You could prepare a 9-patch with a shadow.

To get colored shadows with Carbon without a release you can use JitPack. You can specify a dependency using a commit hash. I didn't try that, but it should work fine.

https://jitpack.io/#ZieIony/Carbon

    allprojects {
        repositories {
            ...
            maven { url 'https://jitpack.io' }
        }
    }

    dependencies {
        compile 'com.github.ZieIony.Carbon:carbon:7fdaccdbd1'
    }

Note that:
 - you're trading stability for new features
 - 0.15.0 will require AS 3.0, data binding 3.0 and Gradle 4.1
 - 0.15.0 introduces some minor breaking changes in styles and API

**Comment by toXel** [comment]
Okay thank you I'll try this out and test it very thoroughly.

**Comment by ZieIony** [comment]
0.15.0 (with colored shadows) is on Maven
