### ISSUE TITLE
No Material buttons on <21 API

### ISSUE THREAD

**Issue by carstenhag** [ZieIony/Carbon#30]
Hi, just trying out this lib. I'm trying to get material buttons with ripple effect on 4.1 (API 16) or up but only ugly normal ones show up.

Emulator with API19 on the left side, layout.xml on the right side.

![0](http://i.imgur.com/SfnFrGn.png)

Neither buttons have ripple.

Using a API 21 emulator both buttons have ripple effect and look like Material Buttons.

**Comment by carstenhag** [comment]
I guess I have to manually set this stuff? Would be nicer of course if it were automatic. Material-Dialogs does this automagically.

**Comment by ZieIony** [comment]
Carbon adds ripples and shadows automatically, when using one of the supplied themes. Each theme specifies carbon_rippleColor attribute, which enables ripples in compatible componenets. Please check if your theme extends one of the Carbon themes.

The second thing is that if you wish to use shadows rendered by Carbon, you have to replace Android layouts with Carbon equivalents. Shadows are drawn by layouts containing shadow casters.

**Comment by ZieIony** [comment]
no answer for 7 days - closing
