### ISSUE TITLE
ProgressBar  onDestroy

### ISSUE THREAD

**Issue by reaper12** [ZieIony/Carbon#303]
demo:https://github.com/reaper12/CarbonTest
if add android:windowAnimationStyle like this:
![1](https://user-images.githubusercontent.com/13657190/27636691-3847b5a0-5c3f-11e7-86f4-d575b3b2d48d.png)

and OneActivity have carbon.widget.ProgressBar ，then OneActivity go to TwoActivity  ，then TwoActivity finish or back to OneActivity，TwoActivity's onDestroy method have delay too long time。if OneActivity not have carbon.widget.ProgressBar or not add android:windowAnimationStyle，It's No problem。

**Comment by ZieIony** [comment]
I have no idea, why that could affect destroying activities. In fact, setting windowAnimationStyle on a phone I just launched your sample doesn't change a thing. The onDestroy method is not very reliable in general, so I wouldn't try to build any behavior on top of it. See: https://developer.android.com/reference/android/app/Activity.html#onDestroy%28%29
