### ISSUE TITLE
ImageView with carbon_ImageView.IconButton style causes crash

### ISSUE THREAD

**Issue by brianliyang** [ZieIony/Carbon#304]
Hi there,

Thanks for this awesome library! I'm trying to integrate it in to my app and I recently ran into an issue I can't seem to figure out. I'm trying to create an `ImageView` button that has a ripple effect (just like the up/back arrow navigation button in the `Toolbar` widget). I looked at the code for the `Toolbar` and attempted to create my own button with the following XML declaration:

XML:
```
<carbon.widget.ImageView
  style="@style/carbon_ImageView.IconButton"
  android:id="@+id/delete_button"
  android:layout_width="wrap_content"
  android:layout_height="wrap_content"
  android:src="@drawable/delete" />
```

Using the `style="@style/carbon_ImageView.IconButton"` line causes the following error:
```
Caused by: java.lang.RuntimeException: Failed to resolve attribute at index 9
 at android.content.res.TypedArray.getColorStateList(TypedArray.java:425)
 at carbon.Carbon.initRippleDrawable(Carbon.java:58)
 at carbon.widget.ImageView.initImageView(ImageView.java:122)
 at carbon.widget.ImageView.<init>(ImageView.java:62)
 at java.lang.reflect.Constructor.newInstance(Native Method) 
 at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
 at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
 at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
 at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
 at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
 at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
 at android.view.View.inflate(View.java:18415) 
 ... (omitted my app-specific stacktrace) ...
```

Removing the `style="@style/carbon_ImageView.IconButton"` line doesn't cause a crash but then I don't get the ripple effect. I don't know if this is a bug, or if I'm using it incorrectly.

If I'm using it wrong, then how do I `ImageView` button with a ripple effect?

By the way, how do create a "small" ripple effect? I'm looking to apply a ripple effect to an icon button, which is about the size of a `CheckBox`. I know the "unbounded" ripple effect can get really large.

Thank you!

**Comment by ZieIony** [comment]
Which version of Carbon are you using? Maven or sources?
Did you set the project up correctly? You need a Carbon theme, RenderScript and some other things. See https://github.com/ZieIony/Carbon/wiki/Installation for details.

Carbon has 'borderless' ripples, which have diameter equal to the distance between left/top and right/bottom corners. To get a small ripple simply use a small view. Borderless ripples are drawn by view's parent, so make sure that the view is inside carbon.widget.*Layout.

**Comment by brianliyang** [comment]
Hey Zielony,

Thanks for getting back so quickly. I've installed the library pretty much just like the installation instructions say:

```
compile 'tk.zielony:carbon:0.14.0'
```

I also have the data binding and RenderScript configurations set. In terms of using the Carbon theme, this is how my app's main theme is set:

```
<style name="AppTheme" parent="carbon_Theme.Light.NoActionBar">
    <item name="android:statusBarColor">@color/carbon_amber_700</item>
    <item name="android:windowBackground">@color/colorBackground</item>
    <item name="colorPrimary">@color/colorPrimary</item>
    <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
    <item name="colorAccent">@color/carbon_cyan_a400</item>
</style>
```

I don't see any Android Studio errors when I use the line `style="@style/carbon_ImageView.IconButton"` so I assume that style asset is properly recognized. 

If you would like, I can try to upload an isolated project that you can clone and try.

**Comment by ZieIony** [comment]
An isolated project would be very helpful

**Comment by brianliyang** [comment]
After trying to create an isolated project, I found what was causing the error before. I forgot to also correctly set the theme in my `v21/styles.xml`. I still have another small issue now, which perhaps you could advise me on. How do I get the ripple effect on my new `ImageView` button?

The isolated project can be found here: [https://github.com/brianliyang/carbon_test](url)

In this project, I just have a simple Carbon `ImageView` that I want to apply a ripple effect to.

**Comment by ZieIony** [comment]
1. Change RelativeLayout to carbon.widget.RelativeLayout - borderless ripples are drawn by parents.
2. Override rippleColor with `?attr/carbon_rippleColor` - by default ripple in IconButton style is white (`?attr/carbon_rippleColorInverse`) and it might be very hard to see on the yellow background.

```
<?xml version="1.0" encoding="utf-8"?>
<carbon.widget.RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.brianliyang.carbontest.MainActivity">

    <carbon.widget.ImageView
        style="@style/carbon_ImageView.IconButton"
        app:carbon_rippleColor="?attr/carbon_rippleColor"
        android:id="@+id/image_button"
        android:layout_width="@dimen/carbon_toolbarItemSize"
        android:layout_height="@dimen/carbon_toolbarItemSize"
        android:layout_centerInParent="true"
        android:src="@drawable/delete" />

</carbon.widget.RelativeLayout>
```

**Comment by brianliyang** [comment]
Thank you very much, that works now!
