### ISSUE TITLE
Setting carbon theme programmatically

### ISSUE THREAD

**Issue by arslancharyev31** [ZieIony/Carbon#308]
Good day. I am extending `carbon.widget.RelativeLayout` and trying to set `CardView` style in the constructor. I tried calling `super(context, null, R.style.carbon_CardView)` , but it didn't work. So what is the right way to apply theme when extending from carbon widgets? Thank you.

**Comment by ZieIony** [comment]
Take a look at [sources of InputLayout](https://github.com/ZieIony/Carbon/blob/master/carbon/src/main/java/carbon/widget/InputLayout.java). It does what you're trying to (and a bit more).

**Comment by arslancharyev31** [comment]
Got it. Thanks a lot.
