### ISSUE TITLE
RelativeLayout have a NullPointerException

### ISSUE THREAD

**Issue by reaper12** [ZieIony/Carbon#310]
if RelativeLayout set android:alpha in xml, will be NullPointerException.
![d42c17f1-5f6a-4122-a263-25f4e130400c](https://user-images.githubusercontent.com/13657190/28606285-c72981ac-7208-11e7-991e-f1bbe0e91365.png)

**Comment by ZieIony** [comment]
Fixed. The fix is on dev branch. Will be merged to master with updated DropDown (most likely this week).
