### ISSUE TITLE
width shadow issue

### ISSUE THREAD

**Issue by wjdrudgh** [ZieIony/Carbon#311]
![2017-07-25 3 47 27](https://user-images.githubusercontent.com/3311928/28658382-06e7d8b0-72e6-11e7-8d4d-00da0c9b6edf.png)

![screenshot_2017-07-25-15-51-17](https://user-images.githubusercontent.com/3311928/28658388-0b321caa-72e6-11e7-9d99-56e5578d9a90.png)

if width is be long, shadow show with 2 lines

**Comment by ZieIony** [comment]
What is exactly the issue? Shadows should be larger at the bottom, because it's shifted a bit due to location of the source of light. Is it about the rounded sides?

**Comment by wjdrudgh** [comment]
no I mean, another shadow show on up and down of target view

![2017-07-27 5 46 22](https://user-images.githubusercontent.com/3311928/28661974-896da1d6-72f3-11e7-8953-e0e63522d630.png)

**Comment by ZieIony** [comment]
These lines are a part of the shadow. Each shadow consists of two parts - a larger one (directional shadow) and a smaller one (ambient shadow). Carbon's shadows aren't perfect and I'm updating them from time to time, but the image you posted looks completely fine. With the current implementation, shadows with larger elevation value tend to look worse. You may want to use smaller elevation values for a better result.

**Comment by wjdrudgh** [comment]
how can I make more spread shadow?

**Comment by ZieIony** [comment]
You can change shadow's size only using elevation and view's size.

**Comment by wjdrudgh** [comment]
I just found something problem.

if view is smaller than 70dp, shadow size is almost correct.
but if view is bigger than 70dp, shadow size is too small than view

**Comment by ZieIony** [comment]
Could you post an example?
