### ISSUE TITLE
ImageView set android:tint not wrok

### ISSUE THREAD

**Issue by reaper12** [ZieIony/Carbon#312]
ImageView set android:tint not wrok

**Comment by ZieIony** [comment]
`android:tint` is not supported on platforms before API 21. Carbon uses its own attribute - `carbon_tint`

**Comment by reaper12** [comment]
but at the same time if set android:background will be have problem

**Comment by ZieIony** [comment]
Why is that? Could you post an example for your issue?

**Comment by reaper12** [comment]
![04fd122c-3e04-42ff-bcdd-8c95adb9840d](https://user-images.githubusercontent.com/13657190/28718258-c0bc68b8-73d7-11e7-9629-973fde22c4c6.png)


<img width="66" alt="qq20170728-210101 2x" src="https://user-images.githubusercontent.com/13657190/28718308-eae8bec0-73d7-11e7-932d-ffc08023274d.png">

**Comment by reaper12** [comment]
I want to like this:
![jietu20170728-210444 2x](https://user-images.githubusercontent.com/13657190/28718413-675d4bce-73d8-11e7-84b5-5da4e2761806.jpg)

**Comment by ZieIony** [comment]
You're right, there's a bug in tint implementation. This line should apply `backgroundTint` instead of `tint`:

https://github.com/ZieIony/Carbon/blob/master/carbon/src/main/java/carbon/widget/ImageView.java#L851

I'll check for this bug in other widgets and push a fix soon.

**Comment by reaper12** [comment]
:)

**Comment by ZieIony** [comment]
fixed
