### ISSUE TITLE
Shadow Color

### ISSUE THREAD

**Issue by rshibley** [ZieIony/Carbon#314]
How do you change the shadow color. It's not recognizing the attribute. Thanks.

**Comment by ZieIony** [comment]
I suppose that you're using `0.14.0` then. The `carbon_elevationShadowColor` wasn't ready in that version. `0.15.0` is not out yet, beacuse it depends on the most recent Android/Gradle tools, which aren't stable yet. If you wish, you can use JitPack, or clone the repo and build an _.aar_ from the most recent sources by yourself.

**Comment by ZieIony** [comment]
0.15.0 (with colored shadows) is on Maven
