### ISSUE TITLE
Error:Error converting bytecode to dex: Cause: PARSE ERROR: InvokeDynamic not supported ...while preparsing cst 004a at offset 00000153 ...while parsing carbon/Carbon.class

### ISSUE THREAD

**Issue by itaispector** [ZieIony/Carbon#317]
Hi,
I'm eagerly trying to use your library in order to solve pre lollipops issues, but I can't compile..

I guess this error:

```
Error:Error converting bytecode to dex:
Cause: PARSE ERROR:
InvokeDynamic not supported
...while preparsing cst 004a at offset 00000153
...while parsing carbon/Carbon.class

Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: 
Unable to pre-dex '/Users/itaispector/.android/build-cache/1c2cf5443800726ef01f4d0bac2f43d0e701ed77/output/jars/classes.jar' 
to '/Users/itaispector/Blm_Android/app/build/intermediates/transforms/dex/debug/folders/1000/10/classes_3f9db9108f021d381bb3b6e882e24b411b11fff5'
```

Do you have any clue about it?

Thanks in advance!

**Comment by ZieIony** [comment]
Hello there!

Are you, by any chance, using Android Studio 2.3? The issue you're experiencing may be connected to Lambdas. You will need Android Studio 3.0 to support that.

**Comment by itaispector** [comment]
@ZieIony Thanks for fast response.

You are correct I'm running Android Studio 2.3.3.
Can I skip updating to 3.0 (since it's beta) and use this solution mentioned here:
https://stackoverflow.com/questions/40080002/invokedynamic-not-supported-when-building-for-android
?

**Comment by ZieIony** [comment]
You can try (because why not!), but I don't have any experience with these methods, so I won't be able to provide further help. From my experience - Retrolambda doesn't work when mixed with Java 8's Lambdas.

The most recent release of Carbon also uses Databinding 3.0. Switching to Android Studio 3.0 might be neccessary. Beta 2 is pretty stable, so I would expect a stable release soon.
