### ISSUE TITLE
Using java 7 with latest carbon version.

### ISSUE THREAD

**Issue by ghost** [ZieIony/Carbon#323]
I have a project using java version 7 but I can not use latest carbon version with it as the latest version using java version 8.

```
Error:Execution failed for task ':iqraaly2:transformClassesWithMultidexlistForPaidDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.android.multidex.ClassReferenceListBuilder with arguments {/home/muhammad/Android/Projects/Work/android-iqraaly-2.0/iqraaly2/build/intermediates/multi-dex/paid/debug/componentClasses.jar /home/muhammad/Android/Projects/Work/android-iqraaly-2.0/iqraaly2/build/intermediates/transforms/jarMerging/paid/debug/jars/1/1f/combined.jar}
```

**Comment by ZieIony** [comment]
This error doesn't look like anything related to Carbon. Is there anything more? Maybe it's an OOM? https://stackoverflow.com/questions/43410408/build-apk-error-apptransformclasseswithdexfordebug

Carbon doesn't need Java 8 as it's supported only by Android API 24+.

**Comment by ghost** [comment]
this happens only when updating to the latest version of carbon.

**Comment by ghost** [comment]
```
Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
...while parsing carbon/BuildConfig.class
```
Here is the log after trying the above solution.

**Comment by ZieIony** [comment]
As you can see in the [`build.gradle`](https://github.com/ZieIony/Carbon/blob/master/carbon/build.gradle), Carbon 0.15.0 was build with Android Studio 3.0 and code compatibility set to 1.8. I suppose that that configuration would be painless. Why can't you use Java 8?

**Comment by ghost** [comment]
I have a lot of difficulties upgrading the project to use java version 8, How I can use carbon with a java 7 project ?
Thanks

**Comment by ZieIony** [comment]
You can't.

**Comment by ghost** [comment]
ok .. thanks anyway
