### ISSUE TITLE
Error:Execution failed for task ':app:processDevDebugManifest'.

### ISSUE THREAD

**Issue by balasaheb143** [ZieIony/Carbon#325]
Error:Execution failed for task ':app:processDevDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.1.0) from [com.android.support:percent:26.1.0] AndroidManifest.xml:25:13-35
  	is also present at [com.android.support:gridlayout-v7:26.0.1] AndroidManifest.xml:25:13-35 value=(26.0.1).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:23:9-25:38 to override.

**Comment by ZieIony** [comment]
Not related to Carbon. You have to use the same versions of Google libraries across the project.
