### ISSUE TITLE
Ripples are missing one important thing

### ISSUE THREAD

**Issue by saket** [ZieIony/Carbon#33]
Hi, thanks for this awesome library. Your implementation of ripples seems to be better than the others. However there's one thing that is missing — the ripple should be canceled as soon as the user moves his finger out of the View (this is how the Lollipop ripples work)

**Comment by ZieIony** [comment]
Thank you, I'm happy you like it.

I don't have any Lollipop device with me right now. I will take a closer look at the ripples when possible.

**Comment by saket** [comment]
Would you like me to record a screencast of Lollipop ripples to have a better understanding?

**Comment by jakub-swierk** [comment]
You mean this? 

http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0B0NGgBg38lWWZGIxcG5melFNSVE/animation-responsiveinteraction-surfacereaction-030202_TouchRipple_DragRelease_xhdpi_002.webm

**Comment by ZieIony** [comment]
I just recorded two short videos showing ripples on Nexus 5 with Lollipop and Galaxy S4 with KitKat. On Nexus you can see the standard system settings screen. On Galaxy S4 - Carbon sample app's main screen. On both videos I'm doing the same thing:
1. Longpress a row
2. Drag to scroll the list
3. Longpress another row
4. Drag to scroll the list
5. Longpress a button
6. Drag to move the finger out of the button's hit area

The videos:
https://www.dropbox.com/s/e15xqwzobqfc1pv/nexuslollipop.mp4?dl=0
https://www.dropbox.com/s/ej66iu8ikhtonw3/galaxykitkat.mp4?dl=0

My animation is slower (I should probably use shorter duration for the animation), but the behavior you described is there. It's done using state animators. When a view with a ripple goes from pressed==true to pressed==false, the ripple is released and fades out.

If the behavior is different in your case, you should check the drawable states and touch events in your layouts. The other possibility is that you have found a bug in the library.

If it's not what you're writing about, please elaborate and attach the screencast.

**Comment by ZieIony** [comment]
this issue is 7 days old with no answers - closing
