### ISSUE TITLE
RecyclerView swiping Error

### ISSUE THREAD

**Issue by amSaadatmand** [ZieIony/Carbon#333]
The items inside the RecyclerView will be error when swiping...

```
FATAL EXCEPTION: main
Process: tk.zielony.carbonsamples, PID: 19850
java.lang.NullPointerException: Attempt to get length of null array
```

**Comment by ZieIony** [comment]
Could you please elaborate on your issue? A more complete stacktrace, steps to reproduce and a sample code would be helpful as well.

**Comment by amSaadatmand** [comment]
Please watch this movie. My Android device is version 7.1.
[https://vimeo.com/253194519](url)

**Comment by amSaadatmand** [comment]
Please help me, I need this :-(   :-(

**Comment by ZieIony** [comment]
I'm sorry, but recently I had no time to think about it. I'm kind of involved into another very exciting project. If your need is that urgent, you can try these solutions:

1. Clone the repo, track down the bug, fix this by yourself and make a pull request. It shouldn't be that hard. This exception is being thrown by my copy of ItemTouchHelper. You can take a look at the official one and try to find the differences. Pros: you get eternal glory for bugfixing open source software. Cons: you have to dive into that code.
2. You can replace this class with the official one to get rid of the crash. Pros: quick and easy fix. Cons: You won't get these nice animations on pre-Lollipop.

By the way, this is certainly a bug as this code works fine with the official classes. I'll try to fix it as soon as possible (like always).

**Comment by ZieIony** [comment]
fixed
