### ISSUE TITLE
RecyclerView swiping Error

### ISSUE THREAD

**Issue by amSaadatmand** [ZieIony/Carbon#334]
The items inside the RecyclerView will be error when swiping...

`FATAL EXCEPTION: main
Process: tk.zielony.carbonsamples, PID: 19850
java.lang.NullPointerException: Attempt to get length of null array`

Please watch this movie. My Android device is version 7.1.
[https://vimeo.com/253194519](https://vimeo.com/253194519)

**Comment by ZieIony** [comment]
duplicate of #333
