### ISSUE TITLE
carbon_htmlText binding

### ISSUE THREAD

**Issue by wbish** [ZieIony/Carbon#337]
Hi,

I'm brand new to the Android dev platform, so please bare with me if this is something obvious :)

I'm trying to do something like this:

```
<carbon.widget.TextView
                    android:id="@+id/lmDescription"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_below="@id/lmTitle"
                    android:maxLines="1"
                    app:carbon_htmlText="@{data.description}"
                    app:carbon_autoSizeText="uniform"/>
```

And I get a compile error saying:

>Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
&gt; android.databinding.tool.util.LoggedErrorException: Found data binding errors.
  ****/ data binding error ****msg:Cannot find the setter for attribute 'app:carbon_htmlText' with parameter type java.lang.String on carbon.widget.TextView.

I was expecting this to just work just like:

`android:text="@{data.description}"`

Is there a quick fix for this or something that is not supported?

**Comment by ZieIony** [comment]
It's not supported. I simply didn't think about that. You can fix it easily though. Either write a custom setter (like this: https://medium.com/google-developers/android-data-binding-custom-setters-55a25a7aea47) or use `Html` class with `android:text`, like this:

`android:text="@{Html.fromHtml(data.description}"`

**Comment by ZieIony** [comment]
I just added a custom binding adapter for carbon_htmlText. Your code should now work no problem.
