### ISSUE TITLE
The compiler errors

### ISSUE THREAD

**Issue by OrangeHao** [ZieIony/Carbon#340]
com.android.builder.dexing.DexArchiveBuilderException: Failed to process D:\AndroidStudio\gradle\gradle-3.5\caches\transforms-1\files-1.1\carbon-0.15.0.1.aar\c8452b19bb5f0446e03a03f83bfd3c6f\jars\classes.jar |  
-- | --
com.android.builder.dexing.DexArchiveBuilderException: Error while dexing carbon/widget/RecyclerView.class |  
com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26) |  

I need help.

**Comment by ZieIony** [comment]
Could you please share your build.gradle? Such error usually means that you're missing Java 1.8 compatibility settings. Like this:

```
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}
```

**Comment by OrangeHao** [comment]
Thanks. It works well. Maybe you should add it into 'Installation', lol.

**Comment by OrangeHao** [comment]
Thanks. It works well. Maybe you could add it into 'Installation', lol.

**Comment by ZieIony** [comment]
Done

Next time please don't close issues by yourself, especially if there's something more to be done :)

**Comment by OrangeHao** [comment]
OK, I got it :)
