### ISSUE TITLE
Program type already present CoordinatorLayout$Behavior

### ISSUE THREAD

**Issue by galibimtiaz** [ZieIony/Carbon#344]
I keep getting this error. I believe its from carbon.

```
Program type already present: android.support.design.widget.CoordinatorLayout$Behavior
Message{kind=ERROR, text=Program type already present: android.support.design.widget.CoordinatorLayout$Behavior, sources=[Unknown source file], tool name=Optional.of(D8)}
```

Here is my current settings.

```
android {

    compileSdkVersion 27
    buildToolsVersion "27.0.3"

    defaultConfig {
        applicationId "com.twiined.galib.pushlocation"
        minSdkVersion 14
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        vectorDrawables.useSupportLibrary = true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    dataBinding {
        enabled = true
    }

}
```

**Comment by ZieIony** [comment]
I would try to mess with support libraries versions. This looks like a known issue: https://stackoverflow.com/questions/49112190/error-program-type-already-present-android-support-design-widget-coordinatorl

Recently I bumped all libs used by Carbon. It's already in the repo. I'll make a release if that's the case.

**Comment by ZieIony** [comment]
So, 0.15.1 (with updated libs) was released a couple of days ago. Did it help? If not, were you able to solve your issue?

**Comment by galibimtiaz** [comment]
I haven't checked it , I will let you.

**Comment by ZieIony** [comment]
0.15.2 with some fixes is available on Maven. I'm closing this issue. Reopen if neccessary.

**Comment by kaushal9678** [comment]
Add in **app/build.gradle**
 **implementation 'com.android.support:design:27.1.0'**
