### ISSUE TITLE
Android Studio 3.2 Canary 14 Build Issue

### ISSUE THREAD

**Issue by poovarasanvasudevan** [ZieIony/Carbon#345]
In Android Studio 3.2 Canary 14 Causes issue with this line , Saying that item tag empty or closed

https://github.com/ZieIony/Carbon/blob/9933974698de488e977ede706e5fd41863837000/carbon/src/main/res/values/ids.xml#L4

**Comment by ZieIony** [comment]
I'm unable to reproduce your issue. I'll work on that a bit more, but I don't want to promise anything. I'm getting a good number of issues using AS 3.2, but in general, I'm not interested in Canary builds. Fixing things for one Canary version usually breaks things for all other users.

**Comment by ZieIony** [comment]
Currently (Canary 18) I'm getting a very similar error, but about `textinput_error` which is defined by Android framework.

**Comment by poovarasanvasudevan** [comment]
Yes @ZieIony  , need to add some prefixes those items

**Comment by ZieIony** [comment]
So, I fixed issues connected to Gradle Plugin 3.2. At least the one with wrong id and another one with duplicated `textStyle` and `textColor` attributes. I'm not sure about `textinput_error`, but the library seems to be building fine.

If you wish to give it a try, you can use the most recent commit and JitPack. If this version will work on both Android Studio 3.1.2 and 3.2, then I'll make a new release.

**Comment by jemshit** [comment]
Same error on `3.2 Beta 1`:
```
carbon-0.15.0.1.aar/925957092a2747252baea95f90c79c70/res/values/values.xml:618:5-49: AAPT: error: <item> inner element must either be a resource reference or empty.
```

**Comment by ZieIony** [comment]
0.15.0.1 is not compatible with AS 3.2. Please update to the latest commit and then try again.

**Comment by ZieIony** [comment]
0.15.2 with fixes is available on Maven
