### ISSUE TITLE
carbon.widget.TextView's  carbon_stroke useless

### ISSUE THREAD

**Issue by EastUp** [ZieIony/Carbon#346]
carbon.widget.TextView's  carbon_stroke useless

**Comment by ZieIony** [comment]
Could you be a little more specific?

**Comment by EastUp** [comment]
![1527759119 1](https://user-images.githubusercontent.com/17868269/40774584-92aa8212-64f8-11e8-9e77-df7e7b046e52.jpg)
this attribute can't work,i also find EditextView dose not implement RoundedCornersView,
next version will fix those ,right?

**Comment by ZieIony** [comment]
Both stroke for TextView and rounded corners for EditText work fine. I'm attaching the screenshot. Please make sure, that you're using the most recent version and one of Carbon's themes.

![image](https://user-images.githubusercontent.com/10180628/40790835-47caa760-64f6-11e8-905d-b8bde8bae04b.png)

**Comment by EastUp** [comment]
I think i'm using the most recent version
but this Editext not implements RoundedCornersView,TextView not implements StrokeView

**Comment by EastUp** [comment]
![2](https://user-images.githubusercontent.com/17868269/40833935-e429199a-65c1-11e8-8701-5c9363d7c49e.png)
![cbc8f22e28410e7cdf86ff5216a54ad](https://user-images.githubusercontent.com/17868269/40833936-e45bc304-65c1-11e8-9d58-cde0bc906dd3.png)


I think i'm using the most recent version
but this Editext not implements RoundedCornersView,TextView not implements StrokeView

**Comment by ZieIony** [comment]
Rounded corners for EditText and stroke for TextView were added and are present in the repository. There wasn't a release though. I just released 0.15.1 with these changes. It should be on Maven in a couple of minutes.
