### ISSUE TITLE
How to add elevation to view from another library?

### ISSUE THREAD

**Issue by fonixer** [ZieIony/Carbon#354]
I tried adding it using app:carbon_elevation, but it didn't work. I can't extend this library class and add code from the Carbon library for creating shadows.
Is there a way to draw a circular shadow just like this one on the FAB (my view is a round button)?
Or the only thing I can do is using FrameLayout and placing transparent Carbon view with shadow?

**Comment by ZieIony** [comment]
`app:carbon_elevation` doesn't work on its own, so using it with a plain view won't do anything.

If you can't extend the class you're using, then wrapping it into Carbon's FrameLayout seems like the best option.

**Comment by fonixer** [comment]
But setting elevation on the FrameLayout will result with the rectangular shadow.
My button is round. 
Or did you mean putting some round view with rectangular shape behind my button?

**Comment by ZieIony** [comment]
If your button is round, you can just wrap your view in a round FrameLayout. That's pretty easy using Carbon. This:

```
<FrameLayout>
    <RoundButton width="56dp" height="56dp" margin="8dp" elevation="4dp" gravity="bottom|right"/>
</FrameLayout>
```

Should become:

```
<carbon.widget.FrameLayout>
    <carbon.widget.FrameLayout width="wrap_content" height="wrap_content" margin="8dp" carbon_elevation="4dp" gravity="bottom|right" carbon_cornerRadius="28dp">
        <RoundButton width="56dp" height="56dp"/>
    </carbon.widget.FrameLayout>
</carbon.widget.FrameLayout>
```

The outer layout needs to be from Carbon library, because it's drawing the shadow. The inner FrameLayout wraps the widget and casts the shadow.

**Comment by fonixer** [comment]
Perfect. That worked.
Thank you very much for your help and for this amazing library.
