### ISSUE TITLE
Can ViewPagerIndicator have custom colors?

### ISSUE THREAD

**Issue by ildar2** [ZieIony/Carbon#357]
I've seen you mention, that circle colors can be colored with `carbon_tint` attribute, but can you set separate colors for inactive circles?

**Comment by ZieIony** [comment]
Currently no. The entire widget uses the same state of the specified color selector for all circles. I guess I could change this behavior so the selected circle is drawn using selected state and others using enabled state.

**Comment by ZieIony** [comment]
done - you can now use selected/enabled/disabled states of tint selector to tint selected dots properly

**Comment by ildar2** [comment]
I'm not sure how to use it, I've tries setting app:carbon_tint="@drawable/boarding_indicator_colors" to this with many variations of state_enabled, state_selected, state_checked:

```
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item
        android:color="@color/colorPrimary"
        android:state_enabled="true"
        android:state_selected="true" />
    <item
        android:color="@color/red"
        android:state_enabled="true"
        android:state_selected="false" />
    <item
        android:color="@color/viewpager_indicator_not_active" />
</selector>
```
But the result is always the same: selected is filled with red and others are just outlined by the same red color

**Comment by ildar2** [comment]
Update: I actually don't see your changes in the sources for 0.15.2 version...

**Comment by ZieIony** [comment]
The change is in the repository. It's not released yet and I can't change existing releases. You can test the current commit using JitPack or by cloning and building the library by yourself. If you don't want to spend too much time with that, you can wait for the release. I'm quite busy, so it most likely won't happen today, but later this week.

**Comment by ZieIony** [comment]
I finally found a bit of time to release this fix. It should be available in Maven soon.

**Comment by ildar2** [comment]
Got these errors after updating to 0.15.3:
`AAPT2 error: check logs for details`
`error: failed linking references.`

```
error: resource android:attr/dialogCornerRadius not found.
Message{kind=ERROR, text=error: resource android:attr/dialogCornerRadius not found., sources=[C:\Android\user_home\caches\transforms-1\files-1.1\appcompat-v7-28.0.0-rc02.aar\1384d64f9802592414a56e330946b77a\res\values-v28\values-v28.xml:9:5-12:13], original message=, tool name=Optional.of(AAPT)}
```

```
error: resource android:attr/fontVariationSettings not found.
Message{kind=ERROR, text=error: resource android:attr/fontVariationSettings not found., sources=[C:\Android\user_home\caches\transforms-1\files-1.1\appcompat-v7-28.0.0-rc02.aar\1384d64f9802592414a56e330946b77a\res\values\values.xml:1304:5-69], original message=, tool name=Optional.of(AAPT)}
```

```
error: resource android:attr/ttcIndex not found.
Message{kind=ERROR, text=error: resource android:attr/ttcIndex not found., sources=[C:\Android\user_home\caches\transforms-1\files-1.1\appcompat-v7-28.0.0-rc02.aar\1384d64f9802592414a56e330946b77a\res\values\values.xml:1304:5-69], original message=, tool name=Optional.of(AAPT)}
```

Tried updating support library version to 28.0.0-rc01, but with no result

**Comment by ZieIony** [comment]
These attributes are no longer present in Android support library. One of the other libraries you're using is not compatible with support 28. This issue seems to be well known: https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/issues/205
