### ISSUE TITLE
How to set fontPath properly through style or textAppearance?

### ISSUE THREAD

**Issue by Andrei-Stakov** [ZieIony/Carbon#359]
Can anyone give me some pointouts for this problem? Somehow I always stumbled with `error: style attribute 'attr/carbon_fontPath= (aka id.app.co:attr/carbon_fontPath=)' not found.`

**Comment by ZieIony** [comment]
So, I'm back from vacations - I'm sorry for the delay. What is your situation exactly? I just prepared two styles (widget style and text appearance) and both are working fine:

```xml
<style name="test" parent="carbon_TextAppearance.Body1">
    <item name="carbon_fontPath">"carbon/Roboto-Light.ttf"</item>
    <item name="android:textColor">@color/carbon_red_400</item>
</style>

<style name="test2" parent="carbon_TextView">
    <item name="carbon_fontPath">"carbon/Roboto-Light.ttf"</item>
    <item name="android:textColor">@color/carbon_red_400</item>
</style>
```

**Comment by ZieIony** [comment]
Closing. Please reopen if needed.
