### ISSUE TITLE
xxx:compileReleaseJavaWithJavac

### ISSUE THREAD

**Issue by EastUp** [ZieIony/Carbon#361]
![image](https://user-images.githubusercontent.com/17868269/47338922-2491af80-d6cc-11e8-9b80-ba55e9c90010.png)

When my project relies on your library, prepare to upload to bintray error

**Comment by ZieIony** [comment]
Could you please paste these messages as text or translate them for me?

**Comment by EastUp** [comment]
error :xxxxx is abstract and cannot be instantiated
error: requires constant expression

**Comment by ZieIony** [comment]
This error happens when you try to use databinding in a library dependency. If your project is a library and you are trying to use Carbon in it, it may be the reason. I don't think that there's other solution than just removing databinding from Carbon. If it's possible, it will take some time.

**Comment by ZieIony** [comment]
I checked two things yesterday and:
1. RxCarbon compiles fine as a library while depending on Carbon.
2. Removing databinding from Carbon is not possible as it is used in several different places.

**Comment by EastUp** [comment]
thank you  the version 0.15.3 is OK
