### ISSUE TITLE
Execution failed for task ':app:mergeDebugResources'.

### ISSUE THREAD

**Issue by EastUp** [ZieIony/Carbon#362]
when  classpath 'com.android.tools.build:gradle:3.2.1'
![image](https://user-images.githubusercontent.com/17868269/47339080-b26d9a80-d6cc-11e8-91f4-8499192312ee.png)

**Comment by ZieIony** [comment]
Seems like #349 

Please make sure that you're using the most recent version of Carbon and the most recent, stable Android Studio.

**Comment by EastUp** [comment]
api 'tk.zielony:carbon:0.15.0.1'
AndroidStudio 3.2.1

**Comment by ZieIony** [comment]
Carbon 0.15.0.1 is not compatible with Android Studio 3.2.+. Currently the most recent version is 0.15.3

**Comment by EastUp** [comment]
where i can find the recently version.when i want to know

**Comment by ZieIony** [comment]
When you open your build.gradle and there's a newer version, Android Studio suggests it. Also, the readme.md file in this repository always lists the most recent version.

**Comment by EastUp** [comment]
![image](https://user-images.githubusercontent.com/17868269/47360661-a3a1da80-d702-11e8-94a8-74f96ff926f8.png)

readme.md file hint version is 0.15.0.1

**Comment by ZieIony** [comment]
thanks, I updated it just now

**Comment by EastUp** [comment]
you're welcome
