### ISSUE TITLE
.gradle\caches\transforms-1\files-1.1\carbon-0.15.0.1.aar\a1751bb67fdd44b64f3d1271e9d809a6\res\values\values.xml:618:5-49: AAPT: error: <item> inner element must either be a resource reference or empty.

### ISSUE THREAD

**Issue by jomarierafa** [ZieIony/Carbon#372]
cant install need help

**Comment by ZieIony** [comment]
This issue was fixed in 0.15.2, if I'm not mistaken. Please make sure that you're using the most recent stable version of Carbon and Android Studio.

**Comment by jomarierafa** [comment]
thank you sir . problem solved :)
