### ISSUE TITLE
Corner radius

### ISSUE THREAD

**Issue by itsaligadimi** [ZieIony/Carbon#375]
Hi, setting corner radius applies radius to all four corner of view. I want to have radius only on one side. Is it possible to implement this with carbon???
If yes, then how?? I can't find anything in wiki.

**Comment by ZieIony** [comment]
Wiki is pretty outdated, when it comes to details. I don't have enough time to update it.

I started working on it recently. The current version works and supports single rounded and cut corners, but wasn't fully tested yet. It's in the repo, if you want to play with it. Check out widgets -> buttons.

<img src="https://user-images.githubusercontent.com/10180628/50643957-cdcc1000-0f6f-11e9-9c33-ef019057c176.png" width="135px" height="240px"/>
