### ISSUE TITLE
Unable to build 

### ISSUE THREAD

**Issue by ankit010cse80** [ZieIony/Carbon#377]
AGPBI: {"kind":"error","text":"Original attribute defined here.","sources":[{"file":"/Users/ankit/.gradle/caches/transforms-1/files-1.1/appcompat-v7-28.0.0.aar/0b281f2cbdc33fad32c8f83e802a0829/res/values/values.xml"}],"original":"","tool":"AAPT"}
:app:processDebugResources FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:processDebugResources'.

Android Studio 3.3.1

**Comment by ZieIony** [comment]
The questions is, which value is duplicated. That is missing in your report. It should be somewhere in the error message.

**Comment by ankit010cse80** [comment]
`  <dimen name="abc_action_bar_content_inset_material">16dp</dimen>` , Android studio was pointing towards this line

**Comment by ZieIony** [comment]
Carbon doesn't declare, nor use this attribute anywhere and the project builds fine for me. If you're trying to build a clone without any modifications, then it should work without any problems. In other cases this looks like a dependency conflict. See: https://stackoverflow.com/questions/53778675/android-support-library-build-v26-x-x-build-error-attribute-fontfamily-alread
