### ISSUE TITLE
AndroidX

### ISSUE THREAD

**Issue by coffee3689** [ZieIony/Carbon#378]
Hi, i need a version to support android x,
i found the code is already supported,
but the current version is old that is not support android x,
if you have free time, update it.

thanks! 
have a good day!

**Comment by ZieIony** [comment]
You can use JitPack to download current master as .aar to your project. For now this is the fastest option you have.

When it comes to the new version, I'm a little bit constrained by Material Components. The most recent code uses MaterialShapeDrawable (from Material Components) for colored shadows, but it's not the best code in the world. I'm checking from time to time if it was fixed, but seems like it's not on top of the priority list for Google. I don't want to release a new version if I know that it's not working as intended.

**Comment by coffee3689** [comment]
Copy that, thanks!

**Comment by ZieIony** [comment]
So, I just uploaded Carbon 0.16.0, which uses androidx. It's still not as stable and polished as I would like to, but Material Components move too slow for me to wait. I hope to fix any issues in the future. The ones I know about currently affect mostly Android 4.x devices.
