### ISSUE TITLE
add diffuse shadow feature

### ISSUE THREAD

**Issue by ghost** [ZieIony/Carbon#381]
Thanks for your wonderful project, it helps us much to solve the ripple effect and shadow problems in platform below Lollipop. But we meet a problem when we want to realize diffuse shadow effect like [this](https://github.com/armcha/ColoredShadowImageView). The realize also give ImageView extra paddings, when the paddings are removed, the edge will seems very clear and of course it is not the effect we want. We worked but don't know how to solve this problem. Can you give us some suggestion?

**Comment by ZieIony** [comment]
I'm happy that my project is useful for you.

I'm not sure, if I understand correctly, what you're asking for. You need this blurred outline, like the library you linked provides. You'd like to achieve that using Carbon, right? Or maybe you'd like to use ColoredShadowImageView with Carbon together?

If you'd like to achieve that effect using only Carbon, then it's not possible. Carbon draws simple gradients around views using only their shapes. It's a technique borrowed from Material Components, so it has the same advantages and limitations - it's very fast, but supports only simple shapes and only one color.

ColoredShadowImageView uses RenderScript to blur provided images and draw them beneath the base image. Some padding is needed, so the blurred outline is not cut by view's bounds. It should be perfectly fine to use ColoredShadowImageView with Carbon.

**Comment by ghost** [comment]
Ok, I understand. I mean can we extend a DiffuseShadowView. Carbon has a advantage that the shadow is drawned on parent. So the padding is not needed by ChildView.

**Comment by ZieIony** [comment]
That's true, drawing shadows on parents is nice. It requires a library to provide all kinds of layouts though, so it's not very convenient for smaller libraries like ColoredShadowImageView.

The good news is that it's quite easy to add the technique used by ColoredShadowImageView to carbon.widget.ImageView. There's a method `drawShadow`, which can be used to draw custom shadows: [link](https://github.com/ZieIony/Carbon/blob/master/carbon/src/main/java/carbon/widget/ImageView.java#L590). The default implementation is quite complex, but if you don't need alpha or circular reveal clipping, the code could be much shorter.

Carbon used RenderScript for rendering not so long ago, so there's even a helper class, which you could restore and use to blur images properly (ColoredShadowImageView seems to be missing a software fallback in case RenderScript is not supported): [link](https://github.com/ZieIony/Carbon/blob/901b5e045ae9c6263c8a4a5c3481b5926da23a39/carbon/src/main/java/carbon/shadow/ShadowGenerator.java).

I won't add this to Carbon as it's a very specific feature and it would make Carbon heavier and more complex to integrate for other users. But, if you wish, I can help you with your implementation.

**Comment by JackLauu** [comment]
Thanks for your advice. I use a library to blur bitmap, which will support
software blur. But when I get the 1/4 blur bitmap, what should I do in
parent view to draw the shadow? I try to create a bitmapdrawable and set
bounds to image view size plus some extra padding. But the drawable draw
nothing. Am I use it in a wrong way. How to create a drawable works like
set background and set padding as it is done in ColorShadowImageView?

**Comment by ghost** [comment]
Thanks for your advice. I use a library to blur bitmap, which will support
software blur. But when I get the 1/4 blur bitmap, what should I do in
parent view to draw the shadow? I try to create a bitmapdrawable and set
bounds to image view size plus some extra padding. But the drawable draw
nothing. Am I use it in a wrong way? How to create a drawable works like
set background and set padding as it is done in ColorShadowImageView?

**Comment by ZieIony** [comment]
Well, most of the shadow drawing code stays the same:

```Java
    @Override
    public void drawShadow(Canvas canvas) {
        float alpha = getAlpha() * Carbon.getDrawableAlpha(getBackground()) / 255.0f * Carbon.getBackgroundTintAlpha(this) / 255.0f;
        if (alpha == 0)
            return;

        if (!hasShadow())
            return;

        float z = getElevation() + getTranslationZ();

        int saveCount;
        boolean maskShadow = getBackground() != null && alpha != 1;
        boolean r = revealAnimator != null && revealAnimator.isRunning();

        paint.setAlpha((int) (127 * alpha));
        saveCount = canvas.saveLayer(0, 0, canvas.getWidth(), canvas.getHeight(), paint, Canvas.ALL_SAVE_FLAG);

        if (r) {
            canvas.clipRect(
                    getLeft() + revealAnimator.x - revealAnimator.radius, getTop() + revealAnimator.y - revealAnimator.radius,
                    getLeft() + revealAnimator.x + revealAnimator.radius, getTop() + revealAnimator.y + revealAnimator.radius);
        }

        Matrix matrix = getMatrix();

        canvas.drawBitmap(blurredImage, getLeft()-radius, (int)(getTop() -radius + z / 2), paint);    // the only change

        if (saveCount != 0) {
            canvas.translate(this.getLeft(), this.getTop());
            canvas.concat(matrix);
            paint.setXfermode(Carbon.CLEAR_MODE);
        }
        if (maskShadow) {
            cornersMask.setFillType(Path.FillType.WINDING);
            canvas.drawPath(cornersMask, paint);
        }
        if (r) {
            canvas.drawPath(revealAnimator.mask, paint);
        }
        if (saveCount != 0) {
            canvas.restoreToCount(saveCount);
            paint.setXfermode(null);
            paint.setAlpha(255);
        }
    }
```

You also need to prepare the blurred drawable:
```
Bitmap blurredImage;
int radius;

void setBlurRadius(int radius){
    this.radius = radius;
}

void setImageBitmap(Bitmap b){
    super.setImageBitmap(b);

    blurredImage = Bitmap.createBitmap(b.getWidth()+radius*2, b.getHeight()+radius*2, Config.ARGB_8888);    // make space for blur
    Canvas c = new Canvas();
    c.drawBitmap(b, radius, radius, paint);
    blurredImage = ShadowGenerator.blur(blurredImage);
}
```

Something like that. You will also need to setup RenderScript and add the blur helper code.
