### ISSUE TITLE
cant run on androidX

### ISSUE THREAD

**Issue by jomarierafa** [ZieIony/Carbon#389]
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class com.google.android.material.animation.AnimationUtils found in modules classes.jar (com.github.material-components:material-components-android:1.1.0-alpha02) and classes.jar (com.google.android.material:material:1.0.0)
  Duplicate class com.google.android.material.animation.AnimatorSetCompat found in modules classes.jar (com.github.material-components:material-components-android:1.1.0-alpha02) and classes.jar (com.google.android.material:material:1.0.0)
  Duplicate class com.google.android.material.animation.ArgbEvaluatorCompat found in modules classes.jar (com.github.material-components:material-components-android:1.1.0-alpha02) and classes.jar (com.google.android.material:material:1.0.0)
  Duplicate class com.google.android.material.animation.ChildrenAlphaProperty found in modules classes.jar (com.github.material-components:material-components-android:1.1.0-alpha02) and classes.jar (com.google.android.material:material:1.0.0)
  Duplicate class com.google.android.material.animation.DrawableAlphaProperty found in modules classes.jar (com.github.material-components:material-components-android:1.1.0-alpha02) and classes.jar (com.google.android.material:material:1.0.0)
  Duplicate class com.google.android.material.animation.ImageMatrixProperty found in modules classes.jar (com.github.material-components:material-components-android:1.1.0-alpha02) and classes.jar (com.google.android.material:material:1.0.0)
  Duplicate class com.google.android.material.animation.MatrixEvaluator found in modules classes.jar (com.github.material-components:material-components-android:1.1.0-alpha02) and classes.jar (com.google.android.material:material:1.0.0)
  Duplicate class com.google.android.material.animation.MotionSpec found in modules classes.jar (com.github.material-components:material-components-android:1.1.0-alpha02) and classes.jar (com.google.android.material:material:1.0.0)
  Duplicate class com.google.android.material.animation.MotionTiming found in modules classes.jar (com.github.material-components:material-components-android:1.1.0-alpha02) and classes.jar (com.google.android.material:material:1.0.0)
  Duplicate class com.google.android.material.animation.Positioning found in modules classes.jar (com.github.material-components:material-components-android:1.1.0-alpha02) and classes.jar (com.google.android.material:material:1.0.0)
  Duplicate class com.google.android.material.appbar.AppBarLayout found in modules classes.jar (com.github.material-components:material-components-android:1.1.0-alpha02) and classes.jar (com.google.android.material:material:1.0.0)
  Duplicate class com.google.android.material.appbar.AppBarLayout$1 found in modules classes.jar (com.github.material-components:material-components-android:1.1.0-alpha02) and classes.jar (com.google.android.material:material:1.0.0)
  Duplicate class com.google.android.material.appbar.AppBarLayout$BaseBehavior found in modules classes.jar (com.github.material-components:material-components-android:1.1.0-alpha02) and classes.jar (com.google.android.material:material:1.0.0)
  Duplicate class com.google.android.material.appbar.AppBarLayout$BaseBehavior$1 found in modules classes.jar (com.github.material-components:material-components-android:1.1.0-alpha02) and classes.jar (com.google.android.material:material:1.0.0)

**Comment by ZieIony** [comment]
It looks like you are using both Material Components from github and from Google's repository. Carbon used github in version 0.16.0: https://github.com/ZieIony/Carbon/commit/78b0a432bd49edc7a6a13ce111cab274085d1693

Please check your 'build.gradle' for the dependencies I mentioned. Remember that it can be a transitive dependency.

**Comment by ZieIony** [comment]
No answer for 7 days - closing. In case of new information please reopen the issue.
