### ISSUE TITLE
error in updating gradle and android version

### ISSUE THREAD

**Issue by Azinnilchi** [ZieIony/Carbon#390]
hi, I used this library with 3.0.1 Gradle version and android 27 API. I want to update my project to the newest version of android and Gradle. at first, when I try to build my Gradle and sync it, it  's ok and syncs successfully, but when I try to run my app, I get this error :

`Android resource compilation failed
*/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:1034: error: <item> inner element must either be a resource reference or empty.
*/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml: error: file failed to compile.`

the line which in pointet is this : 
`<item name="carbon_input" type="id">1</item>`

so what is the problem?!

**Comment by ZieIony** [comment]
Which version of Carbon are you using? Your issue looks like a #372

**Comment by Azinnilchi** [comment]
I'm using 0.15.0.1 because I can't update the library ! it has conflict in some attr with some other libraries cause their name is not unique. I've tried 15.3 and 15.2. it's not possible for me to update.
for example one of the conflicts is : 
`error: duplicate value for resource 'attr/chipCornerRadius' with config ''.`

**Comment by ZieIony** [comment]
Carbon does not use nor declare that attribute, so the conflict is generated by a transitive dependency. Most likely by Material Components. The problem is that Material Components is distributed using github, Google's Maven and using older Maven imports. You can look for confliting dependencies using gradle: https://stackoverflow.com/questions/21645071/using-gradle-to-find-dependency-tree

**Comment by Azinnilchi** [comment]
when I don't update this library and Gradle, there is no conflict, as I update it, conflict is shown. I mean when I only want to update this library, conflict is made.so you're suggesting this conflict is irrelevant to this library?!

**Comment by ZieIony** [comment]
As I wrote, Carbon does not use nor declare that attribute, so the conflict is generated by a transitive dependency. Carbon's dependencies change between versions and that may be the source of the issue. If not the dependencies, then maybe changes in build tools or the toolchain. Android tools have tons of between version incompatibilities.

**Comment by Azinnilchi** [comment]
I updated carbon to 0.15.3, step by step. I don't understand how it worked, but I could update in now. thanks for your help. but all my colored shadow turned to grey now.
