### ISSUE TITLE
cornerRadius is not working when creating screen shot

### ISSUE THREAD

**Issue by ghost** [ZieIony/Carbon#400]
When I use drawing cache to create screen shot, I found cornerRadius will dismiss on Android Lollipop  or later. The code is below:
```
fun getScreenShot() {
    val dView = (context as Activity).window.decorView
    dView.isDrawingCacheEnabled = true
    dView.setWillNotCacheDrawing(false)
    setImageBitmap(Bitmap.createBitmap(dView.drawingCache, 0, 0, width, height))
    dView.destroyDrawingCache()
}
```
I think it is a problem cause by the internal render mechanism.

**Comment by ZieIony** [comment]
Hardware composition effects don't appear on screenshots taken using that method. This is an issue related to Android framework, not to Carbon. It's possible to fix it using a couple of tricks and Carbon used to do that using RenderingMode settings. Unfortunatelly for your case, I removed RenderingMode together with RenderScript and currently I don't plan to implement it back. See: #281 

Taking screenshots from code is currently done using PixelCopy. You may want to take a look at that: https://medium.com/@shiveshmehta09/taking-screenshot-programmatically-using-pixelcopy-api-83c84643b02a
