### ISSUE TITLE
Cant show shadow effect 

### ISSUE THREAD

**Issue by berromendoza** [ZieIony/Carbon#402]
The link of my question 

https://stackoverflow.com/questions/60511574/what-is-the-correct-way-to-install-the-carbon-library-for-android

Help please

**Comment by ZieIony** [comment]
Shadows in Carbon went through a couple of changes since 0.16.0.1. Did you try to compile the sample app and run it on your device? If it works, you could use the most recent commit of Carbon instead of 0.16.0.1.

**Comment by ZieIony** [comment]
I'm sorry, but I cannot help you without any additional information from your side.
