### ISSUE TITLE
 Carbon shadow can be applied to a navigation view??

### ISSUE THREAD

**Issue by berromendoza** [ZieIony/Carbon#404]
I am trying to apply the carbon shadow to a com.google.android.material.navigation.NavigationView but I have not been successful, the shadow is not reflected correctly, is it possible to do it? or the bookstore is not designed for that?

**Comment by ZieIony** [comment]
The way Carbon supports shadows requires both the shadow caster and the shadow receiver to implement certain Carbon interfaces. Google views don't support that. To get shadow cast by a view you need to use a Carbon view, or extend the view and implement ShadowView, or wrap that view in a Carbon layout.
