### ISSUE TITLE
Click range

### ISSUE THREAD

**Issue by leepeozzz** [ZieIony/Carbon#407]
Hope to expand the click range, and expand ripple effect.

**Comment by ZieIony** [comment]
Could you explain more precisely, what is your issue?

**Comment by leepeozzz** [comment]
![2020-04-21](https://user-images.githubusercontent.com/31857860/79808413-01ea6080-836e-11ea-9af0-1ea0acde2b5f.png)

In order to expand the ripple effect, I will setPadding, but sometimes it causes trouble. I want to setMargin, bun the ripple effect will become smaller. How to solve it?

**Comment by leepeozzz** [comment]
> Could you explain more precisely, what is your issue?

In order to expand the ripple effect, I will setPadding, but sometimes it causes trouble. I want to setMargin, bun the ripple effect will become smaller. How to solve it?

![捕获](https://user-images.githubusercontent.com/31857860/79808743-082d0c80-836f-11ea-91d3-9105997a0c8f.JPG)

**Comment by ZieIony** [comment]
There's nothing you can do about it except adjusting your layouts so the padding woks. Ripple is a Drawable and is set as the view's background. It's always constrained to its owner's bounds. Padding is handled by the View class and it makes it bigger. Margin is handled by layouts, so it just moves views a little. That's the reason of the effect you're observing.

**Comment by leepeozzz** [comment]
Set rippleDrawable bounds and draw by parentView. Is this possible?

**Comment by ZieIony** [comment]
Sure. It would be quite hard to manage, but definitely possible since Carbon draws shadows like that.

**Comment by leepeozzz** [comment]
Can you add it to Carbon?

**Comment by ZieIony** [comment]
I could, but the implementation of a general case would be quite time-consuming. I think that your use case is easily solvable using what's currently present in the framework. If you wish, I can help you with your layout a little.
