### ISSUE TITLE
Shadows do not work for Android 8 and below when the shadow color is set

### ISSUE THREAD

**Issue by michaelChicherin** [ZieIony/Carbon#413]
Shadows does not work for Android 8 and below when app:carbon_elevationShadowColor attribute is set.
I've tested on api 26 and lower. Shadows shows only when I remove attribute app:carbon_elevationShadowColor 
Works well on api 29

There is closed ticket about the same problem. https://github.com/ZieIony/Carbon/issues/406
I've tried different versions of carbon, neither works

**Comment by ZieIony** [comment]
Maybe you could prepare a minimal working example of your issue then?

**Comment by michaelChicherin** [comment]
Hi ZieIony,

Sorry, my mistake. **The solution is to change widget of direct parent to carbon widget**. On 29 api shadow color works with non-direct parent, so it confused me.
Thank you for your time. You've made really great tool!

**Comment by ZieIony** [comment]
That's what I suspected. On API 29+ colored shadows are supported natively by the system. That's why it works without any extra steps.
