### ISSUE TITLE
android:textAppearance Does not apply font family.

### ISSUE THREAD

**Issue by michaelChicherin** [ZieIony/Carbon#416]
Hello.

When using <carbon.widget.TextView and setting android:textAppearance to a style that applies custom fontFamily - the font family wont apply to the widget. However it works with native textview widget.

on this pic you see native textview(top) and <carbon.widget.TextView with exactly the same attributes.
![image](https://user-images.githubusercontent.com/56351279/87755626-2351d000-c829-11ea-8245-c2c123245800.png)

**Comment by ZieIony** [comment]
Carbon uses a custom attribute called `carbon_font` for that. `android:fontFamily` does not support font resources and downloadable fonts on Android 4.0. It also works differently - you can provide a string name of a desired font family. To make these things clear Carbon provides its own attribute for that.

**Comment by michaelChicherin** [comment]
Thanks a lot!
