### ISSUE TITLE
How can we use it?

### ISSUE THREAD

**Issue by Naguchennai** [ZieIony/Carbon#417]
How can we use it?
no code no explain.. what is this actually ?

**Comment by ZieIony** [comment]
Hello!

I know that the documentation is not exhaustive, but I wouldn't say that there's no info at all.

* There's a [README.md](https://github.com/ZieIony/Carbon/blob/master/README.md) file on the main page with an introduction to this project and a couple of screenshots.
* On wiki there's an [installation guide](https://github.com/ZieIony/Carbon/wiki/Installation) and other things to read.
* The repository contains a big number of [samples](https://github.com/ZieIony/Carbon/tree/master/samples) you can study and copy from.

If that's not enough, please be more specific with your needs and I'll try to help.

Cheers!
