### ISSUE TITLE
Shadow not working on API 23 device

### ISSUE THREAD

**Issue by dovahkiin98** [ZieIony/Carbon#423]
As I read in the code and library description, this library is aimed to create consistant View attributes on all Android platforms and versions, including Shadow, Stroke, and etc

I used the library on an Android 29 device, and it worked fine. But when I moved to an Android 23 device, the Shadow didn't even draw. It's not that the shadow color didn't change, which would be understandable considering colored shadows are API 28 feature, but there is no shadow, at all

![Screenshot_1610541006](https://user-images.githubusercontent.com/8161112/104452566-dcf8e600-55ab-11eb-9ea4-a606879cc644.png)

This is a view containing 3 items. A coded Card View with a carbon.widget.FrameLayout, the normal MaterialCardView, and an XML carbon.widget.FrameLayout.

Only the MaterialCardView is showing shadow.

```XML
        <carbon.widget.FrameLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="center"
            app:carbon_elevation="16dp"
            app:carbon_cornerRadius="16dp"
            android:background="@color/carbon_white"
            app:carbon_elevationShadowColor="@color/carbon_red_700"
            app:layout_behavior="@string/appbar_scrolling_view_behavior">

            <TextView
                android:layout_width="wrap_content"
                android:text="Hello World"
                android:layout_gravity="center"
                android:gravity="center"
                android:layout_height="80dp" />
        </carbon.widget.FrameLayout>
 ```

```Kotlin
        elevation = resources.toDp(16f)
        setCornerRadius(resources.toDp(10))
        setBackgroundColor(Color.WHITE)
        elevationShadowColor = ColorStateList.valueOf(0xFF1F54C3.toInt())
```

 I added the library as `api`, even changed the theme of the app. It doesn't show.

What is wrong? Is this not what the library is meant to do? Or am I implementing something wrong?

**Comment by ZieIony** [comment]
Could you comment what was your problem and solution? Colored shadows should work fine on all API levels.

**Comment by dovahkiin98** [comment]
The parent of the view was a Linear Layout, not a Carbon Linear Layout
