### ISSUE TITLE
This feature is implemented using reflection

### ISSUE THREAD

**Issue by Anshadalikm** [ZieIony/Carbon#425]
- device: OnePlus ONEPLUS A6010, API 29
     - method: carbon.widget.EditText.setCursorColor(...)
     - cause: java.lang.NoSuchFieldException: No field mCursorDrawable in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes3.dex) at getDeclaredField(Class.java:-2)

**Comment by ZieIony** [comment]
This method was removed from Carbon a long time ago. You seem to be using the version that is still available on Maven. I recommend just building the master branch of this repository either manually or with JitPack - it's stable and contains plenty of fixes.

**Comment by ZieIony** [comment]
Duplicate of #424
