### ISSUE TITLE
Can carbon show shadow without layout_margin

### ISSUE THREAD

**Issue by chinalwb** [ZieIony/Carbon#430]
Hi @ZieIony , first of all, thanks very much for this amazing library!

Second, awesome work on the Drop shadow implementation, you made the shadow easy!

I have a question, while introducing drop shadow to my project, I found the shadow cannot be shown unless I have set `layout_margin` .

Is `layout_margin` essential for drop shadow displaying?

If yes, is there a way I can show shadow but don't set margin for my view?

P.S.: I am laying out my views programmatically, that is to say, for some cases I want to have shadow but not for others; currently I found it is a pain to calculate whether to add a margin (for shadow), so it'll be great if the shadow can be shown correctly with or without setting the margins.

Great work! Thank you sir!

**Comment by ZieIony** [comment]
Well, I think it's about a bug I fixed a couple of days ago, which caused shadows to be cut when there was not enough space around a view. Did you try using the most recent code from this repository? You can either clone it and build a library yourself, or use JitPack to download a compiled version right to your project.

**Comment by chinalwb** [comment]
@ZieIony Thank you very much for the reply!

I synced down the latest code, and I saw the commit:


But still, the issue exists:

![image](https://user-images.githubusercontent.com/1758864/115655563-1ccb2880-a366-11eb-98e4-c9f6bd651345.png)


Code:

```
<carbon.widget.LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        android:layout_marginLeft="64dp"
        android:layout_marginRight="64dp"
        android:clipChildren="false"
        android:clipToPadding="false"
        >

        <carbon.widget.Button
            android:layout_width="match_parent"
            android:layout_height="56dp"
            android:layout_marginTop="0dp"
            app:carbon_cornerRadiusTopStart="20dp"
            app:carbon_cornerRadiusTopEnd="20dp"
            app:carbon_cornerRadiusBottomEnd="0dp"
            app:carbon_cornerRadiusBottomStart="0dp"
            app:carbon_strokeWidth="0.2dp"
            app:carbon_stroke="@color/carbon_purple_a400"
            android:background="#ffffff"
            app:carbon_elevationShadowColor="@color/carbon_deepPurple_700"
            app:carbon_elevation="4dp" />

        <carbon.widget.Button
            android:layout_width="match_parent"
            android:layout_height="56dp"
            android:layout_margin="0dp"
            android:background="#ffffff"
            app:carbon_elevation="4dp"
            app:carbon_strokeWidth="0.2dp"
            app:carbon_stroke="@color/carbon_purple_a400"
            app:carbon_cornerRadius="0dp"
            app:carbon_elevationShadowColor="@color/carbon_deepPurple_700"
            />

        <carbon.widget.Button
            android:layout_width="match_parent"
            android:layout_height="56dp"
            android:layout_marginBottom="0dp"
            android:background="#ffffff"
            app:carbon_elevation="16dp"
            app:carbon_strokeWidth="0.2dp"
            app:carbon_stroke="@color/carbon_purple_a400"
            app:carbon_cornerRadiusTopStart="0dp"
            app:carbon_cornerRadiusTopEnd="0dp"
            app:carbon_cornerRadiusBottomStart="20dp"
            app:carbon_cornerRadiusBottomEnd="20dp"
            app:carbon_elevationShadowColor="@color/carbon_deepPurple_700"
            />

    </carbon.widget.LinearLayout>
```


I expect it to be like:
![image](https://user-images.githubusercontent.com/1758864/115655792-96631680-a366-11eb-8567-4c54bf304ca6.png)

But I have to add margins to buttons, code will look like:

```

    <carbon.widget.LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        android:layout_marginLeft="0dp"
        android:layout_marginRight="0dp"
        android:clipChildren="false"
        android:clipToPadding="false"
        >

        <carbon.widget.Button
            android:layout_width="match_parent"
            android:layout_height="56dp"
            android:layout_marginTop="0dp"
            android:layout_marginLeft="64dp"
            android:layout_marginRight="64dp"
            app:carbon_touchMarginTop="16dp"
            android:layout_marginBottom="0dp"
            app:carbon_cornerRadiusTopStart="20dp"
            app:carbon_cornerRadiusTopEnd="20dp"
            app:carbon_cornerRadiusBottomEnd="0dp"
            app:carbon_cornerRadiusBottomStart="0dp"
            app:carbon_strokeWidth="0.2dp"
            app:carbon_stroke="@color/carbon_purple_a400"
            android:background="#ffffff"
            app:carbon_elevationShadowColor="@color/carbon_deepPurple_700"
            app:carbon_elevation="4dp" />

        <carbon.widget.Button
            android:layout_width="match_parent"
            android:layout_height="56dp"
            android:layout_marginLeft="64dp"
            android:layout_marginRight="64dp"
            app:carbon_touchMarginTop="0dp"
            android:layout_marginBottom="0dp"
            android:background="#ffffff"
            app:carbon_elevation="4dp"
            app:carbon_strokeWidth="0.2dp"
            app:carbon_stroke="@color/carbon_purple_a400"
            app:carbon_cornerRadius="0dp"
            app:carbon_elevationShadowColor="@color/carbon_deepPurple_700"
            />

        <carbon.widget.Button
            android:layout_width="match_parent"
            android:layout_height="56dp"
            android:layout_marginLeft="64dp"
            android:layout_marginRight="64dp"
            android:layout_marginTop="0dp"
            android:layout_marginBottom="16dp"
            android:background="#ffffff"
            app:carbon_elevation="8dp"
            app:carbon_strokeWidth="0.2dp"
            app:carbon_stroke="@color/carbon_purple_a400"
            app:carbon_cornerRadiusTopStart="0dp"
            app:carbon_cornerRadiusTopEnd="0dp"
            app:carbon_cornerRadiusBottomStart="20dp"
            app:carbon_cornerRadiusBottomEnd="20dp"
            app:carbon_elevationShadowColor="@color/carbon_deepPurple_700"
            />

    </carbon.widget.LinearLayout>
```

I'd say it works perfect if the layout is static and it can be pre-built by developers, with the power of Carbon, for setting the margins is like stealing candy from a baby, but for me, my app is data-driven, and same to the drop shadows on Buttons (actually I am using the shadow-able Carbon LinearLayout heavily), these shadow-able LinearLayout can be laid out vertically or horizontally one by one, with or with no drop shadows on them, if I have to take extra margins into account, for displaying the LinearLayout with shadow, then the logic would be too complex.

Assume such a scenario, say one shadowed LinearLayout, another one shadowed to the right; but one not shadowed to the bottom etc. I have to set margin left to the 1st but no to the right because the 2nd (at right) also has shadow, and for the 2nd one, I have right margin for shadow; same logic to the one below, but logic gets complex here, that why I am asking for a solution here, if the drop shadow can be visible without depending on the margins/paddings, that'd be wonderful for me.

Thanks again!!

**Comment by chinalwb** [comment]
Hi @ZieIony , I found the trick!

Via my testings, it depends on two parts.

1. I need to set `clipChildren = false` on all of the ancestor containers.
2. I need to use your theme `carbon_Theme.Light.DarkPrimaryColor.NoActionBar`


![shadow_gif](https://user-images.githubusercontent.com/1758864/115821320-27082800-a435-11eb-82ed-d6bcf60d4c32.gif)

I'll go deeper to try it out in my project and let you know!

BTW, this needs your latest code, in the recording above I included your `carbon` library into my project. I found the latest release of Carbon is 0.16.0.1, it has not been updated since laster year, but you've added many awesome features definitely! Looking forward to new release!

**Comment by chinalwb** [comment]
Hey @ZieIony , hope all going well with you!

I figured out the issue in my project, it turns out that I need to include `clipChildren=false` for the parent of the view want to be shadowed, but the tricky point is, not only the direct parent view group but also all of the ancestors.

I am closing this issue.

BTW, I'd want to know is there any release plan for the most recent changes?

Thank you!

**Comment by ZieIony** [comment]
Using `clipChildren = false` makes sense, I'm glad that you were able to solve this riddle.

The release plan is, as you could already see, a little suspended. I suppose I could release 0.17.0 as it is, since this version seems to be pretty stable and has a couple of interesting improvements. On the other hand there's a ton of things I didn't implement yet, I have never managed to prepare a decent documentation, and I can't keep up with features (and bugs) added by Google every couple of weeks. Also, I'm not using Carbon for any project now, and that was my main reason for making it in the first place. That's why I'm not spending as much time with Carbon now as I used to, and I'm not releasing any new versions.

At this moment it's mostly a source of Android UI building blocks, interesting techniques, and bugfixes, that stays online and open for everyone. I'll try to update it, respond to the users, and try to fix stuff as long as it is reasonable.

I'm currently more focused on another project. UI is also an important part of it (and this time I implemented every bit of it from scratch), but it's not Android-related at all: https://twitter.com/GreenMakesApps/status/1342280680483545095).

**Comment by chinalwb** [comment]
Hey man! How're you doing?

Thanks for sharing the plan, looking forward to the `0.17.0` release.

I watched the video, Ghurund is awesome!!

It looks like you are creating a new language 🔥🔥🔥

One of the use case I can see is she can be pretty helpful for the prototype design tools. Of course I believe she can do more!

AWESOME WORK!!
