### ISSUE TITLE
Any plan for 0.17.0?

### ISSUE THREAD

**Issue by chinalwb** [ZieIony/Carbon#432]
Hi @ZieIony Good morning sir! Hope everything goes well for you.

Sorry to bother you but I just want to check is there any plan for 0.17.0 release? I saw you had updated the version to 0.17.0 in build.gradle in March, but haven't released it yet. 
I am working on a project which depends heavily on Carbon, and I know I can checkout the code and build from my local, yes I did like this (because I need features in the latest version) and this has been working perfect for me for a long time in my application project, now I'll need to convert my project into a library, but in this way I am running into a trouble which is I cannot have the carbon.aar inside my aar file. Hence I am wondering if there is any plan for the 0.17.0 release? Thank you!

Have a nice day, sir!

**Comment by ZieIony** [comment]
Well, I guess I could finally release it to Maven. I'll try to do that this weekend.

**Comment by chinalwb** [comment]
Sounds great! Thanks!

**Comment by ZieIony** [comment]
done

**Comment by chinalwb** [comment]
Awesome!! Thanks!!
