### ISSUE TITLE
Views with corner didn't show up in some devices

### ISSUE THREAD

**Issue by devabir93** [ZieIony/Carbon#435]
Hello, I am using this amazing library in my app but I am facing a problem. in some devices e.g. galaxy Tab A with android version 11  a view with corners on both sides or three sides didn't show up, but a view with corners for all sides show up well. any help, please?

**Comment by ZieIony** [comment]
For corners Carbon reuses ShapeAppearanceModel from Google's Material Design library. Did you try using more complex corner setups with Google material components? Does it work for you?

**Comment by devabir93** [comment]
When I use ShapeAppearanceModel its working very well 
but when i use xml code like this it didn't work:
`              app:carbon_cornerRadiusBottomEnd="26dp"
                app:carbon_cornerRadiusBottomStart="26dp"
                app:carbon_cornerRadiusTopEnd="0dp"
                app:carbon_cornerRadiusTopStart="26dp"`
i want to mention that its working in some places and almost all devices but expect some devices.

**Comment by ZieIony** [comment]
Hmm, then it can be quite difficult to reproduce. Could you provide me with a minimal example application demonstrating your issue? I could launch it on my device and see if I can find the problem. I don't have a Galaxy Tab A, but hopefully it would happen also on one of my devices or an emulator.
