### ISSUE TITLE
Touch ripple for ImageView

### ISSUE THREAD

**Issue by ZieIony** [ZieIony/Carbon#5]
It should be drawn on top of an image

**Comment by ZieIony** [comment]
Done. RippleDrawable now has three modes. For ImageView pick RippleDrawable.Style.Over

**Comment by saket** [comment]
Zielony, sorry for posting an off-topic question, but do you plan to offer your Material elements as separate modules? I would prefer not to include the whole project only to use ripples.

**Comment by ZieIony** [comment]
I thought about it, but it's not that easy, because almost everything is tightly integrated with other components. For example the ripple. Due to clipping issues in Android < 5.0 it's not possible to draw borderless backgrounds just by setting the background drawable. That's why I would have to export the ripple with all layouts only to make the borderless mode work.

If you wish, you can copy RippleDrawable.java to your project and integrate it with your code manually.

This is quite important issue. I'm going to add this Q&A to FAQ section.

**Comment by saket** [comment]
Got it, thanks. :)
