### ISSUE TITLE
NavigationDrawer elevation doesn't work

### ISSUE THREAD

**Issue by DSteve595** [ZieIony/Carbon#54]
In a situation where setting `android:elevation` on a DrawerLayout's second child (the drawer layout) works fine, setting `carbon_elevation` doesn't show the shadow properly.
After making the drawer transparent, I can see that the shadow is being drawn, but it's too far to the left (where the drawer is sliding out from) and is completely covered by the drawer itself.

**Comment by ZieIony** [comment]
Carbon doesn't feature any drawer, so I suppose you have your own implementation with one of Carbon layouts used as a drawer layout.

My guess is that it's due to shadow casting algorithm. Carbon uses one point light placed at (width/2, -height/2). It means that all views on the left (or right) side of a phone cast shadows shifted to the left (or right). This algorithm doesn't use transformation matrices, so opening the drawer doesn't make the shadow move to the right.

I'm marking this as a bug, Nice finding!

**Comment by DSteve595** [comment]
Yep, I'm using the support lib's DrawerLayout wrapped in a carbon layout.

Thanks so much for the time and effort you put into this library!

**Comment by ZieIony** [comment]
Thank you for your kind words. I really appreciate that!

I just pushed a major release including transformation support for shadow casters. You can try that in ~30 minutes. I'm not sure if it fixes your problem. If not, I can try to prepare a tiny drawer project and debug your case precisely.

**Comment by DSteve595** [comment]
Thanks! I'll check it out asap.

**Comment by DSteve595** [comment]
Looks good to me!
![drawer](https://cloud.githubusercontent.com/assets/1078569/6817261/bcf62db0-d274-11e4-9be9-5fd98ebc87c0.png)

One more thing regarding drawers: [ScrimInsetsFrameLayout](https://github.com/google/iosched/blob/master/android/src/main/java/com/google/samples/apps/iosched/ui/widget/ScrimInsetsFrameLayout.java), a layout Google made to enable the drawer to be tinted underneath the status bar (as in the guidelines), stops working when it's enclosed in a Carbon FrameLayout (which is the only way I could get the shadow to work). It stops short below the status bar. I tried making it extend Carbon's FrameLayout instead of Android's, but it didn't change anything.
My current layout:

```
<carbon.widget.FrameLayout
    android:layout_width="280dp"
    android:layout_height="match_parent"
    android:layout_gravity="start"
    android:fitsSystemWindows="true">

    <mypackage.ScrimInsetsFrameLayout
        android:id="@+id/scrimInsetsFrameLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@android:color/white"
        android:fitsSystemWindows="true"
        app:carbon_elevation="4dp"
        app:insetForeground="#4000">

        <fragment
            android:id="@+id/fragment_drawer"
            android:name="mypackage.DrawerFragment"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </mypackage.ScrimInsetsFrameLayout>
</carbon.widget.FrameLayout>
```

Ideally, it would just be a `carbon.widget.ScrimInsetsFrameLayout` containing the fragment.
Since ScrimInsetsFrameLayout is practically required to implement a Material-style drawer, do you think you could make a Carbon widget of that too?

**Comment by ZieIony** [comment]
I'm glad it helped and thank you for the feedback. I'm closing this issue as fixed.

I would like to prepare a sample with a drawer, so I'm going to need that. I guess it's a good idea to provide a Carbon version of that ScrimInsetsFrameLayout. I've opened an issue for tracking that issue. See: #56
