### ISSUE TITLE
duplicated resource key arises a problem that the project fails building

### ISSUE THREAD

**Issue by doyonghoon** [ZieIony/Carbon#55]
I tried to update from the version, 0.6.0 to the latest version which is 0.7.0 but the project fails compiling because of the duplicated resource key, which is `orientation`. The error message during building gradle is appeared like `Error:Attribute "orientation" has already been defined` and it ceased building. As far as I know, there must be used a unique name for resource id to be used far-reaching in the project. so the key here `orientation` may be changed as `carbon_orientation` or something. Im wondering how others who adopt the latest version of carbon 0.7.0 solve this problem. thanks.

**Comment by ZieIony** [comment]
Carbon doesn't define nor use an 'orientation' attribute, so I'm unable to fix that issue. Maybe you're getting a conflict between Android includes? I would try cleaning the cache and rebuilding the project.

**Comment by doyonghoon** [comment]
Oh, yes. sorry for that. It was my fault. It seems like one of the dependency library that Carbon uses conflicts with my project. I've found that `com.android.support:gridlayout-v7:21.0.3` raises this issue since one of my attribute defined as same key as the `Gridlayout-v7:21.0.3` has. 
thanks for your reply.
