### ISSUE TITLE
Toolbar

### ISSUE THREAD

**Issue by wrozwad** [ZieIony/Carbon#58]
They're a possibility that your Toolbar can extend android.support.v7.widget.Toolbar in place of LinearLayout? I wan't to still use it as a normal action bar by using setSupportActionBar(toolbar)

**Comment by ZieIony** [comment]
Not really. The reason is that by extending LinearLayout I'm getting shadows, ripples and SVG icons for free. android.support.v7.widget.Toolbar and carbon.widget.Toolbar deal with menus and icons in a different way, so extending support Toolbar is not that simple.

**Comment by wswsl** [comment]
Hello, I like your Carbon project very much.But I can't access Dropbox,can you put sample apk on Github?
Thanks!

**Comment by wswsl** [comment]
Sorry,I was wrong...

**Comment by ZieIony** [comment]
ActionBar is a part of Activity with a very specific approach to navigation and layouts. For example ActionBar is placed in a top level layout, which cannot draw shadows on older platforms. That's why carbon.widget.Toolbar cannot be used as a support action bar. I'm thinking about carbon.ToolbarActivity with integrated Toolbar and navigation.

**Comment by ZieIony** [comment]
Actually I was wrong, Toolbar can be placed anywhere and still used as ActionBar. Since today carbon.widget.Toolbar extends android.support.v7.widget.Toolbar and can be used with support things. It's not fully functional yet. I'll be working on it and design widgets in the near future.

**Comment by rhonyabdullah** [comment]
from the example project the Toolbar class extend v7.widget.Toolbar, but when i try to implement it into my project i see the toolbar class still extend the LinearLayout, what should i do ? 
try to rebuild still didn't work.

**Comment by ZieIony** [comment]
I've created a new issue. Your comment was hardly noticable, because it's in an old, closed thread. See: #181
