### ISSUE TITLE
Update ripple animation to Android 5.1's

### ISSUE THREAD

**Issue by DSteve595** [ZieIony/Carbon#59]
The default ripple effect is slightly different in Android 5.1. The ripple moves outwards faster and seems to not slow down (as much) as it reaches the edges like it did in 5.0. I think that's the only difference. It would be nice to have it match the new behavior.

**Comment by ZieIony** [comment]
Good idea.

Could you please record a screencast showing the new ripple? I don't have access to a 5.1 device right now and using the emulator misses the point.

**Comment by DSteve595** [comment]
I don't have a device with it either, just an emulator. I'll record it as
soon as I can.

**Comment by ZieIony** [comment]
Videos for further analysis:
Nexus 5 with Lollipop 5.0.1: https://www.dropbox.com/s/i265j1a8qbnwwrl/ripple50.mp4?dl=0
Nexus 6 with Lollipop 5.1: https://www.dropbox.com/s/v7ekiqg7df4j019/ripple51.mp4?dl=0

**Comment by DSteve595** [comment]
Interesting, the difference doesn't look nearly as drastic as I remember it being on my emulator. I think the difference may be more visible on small views, like `Button`s. My screenrecord isn't working for some reason, I'll try Genymotion.

**Comment by DSteve595** [comment]
![buttons](https://cloud.githubusercontent.com/assets/1078569/6901907/63cd54e8-d6de-11e4-8bf5-82cf79c93c9c.gif)
Sorry for the graphical glitches, they happen only in the emulator.

**Comment by ZieIony** [comment]
Yes, you're right, Carbon uses different algorithm for that. I guess I should just copy the constants from the original ripple.

I suppose that the change you noticed between 5.0 and 5.1 may be connected to the fact that the ripple in 5.0 doesn't use a screen's density. Maybe in 5.1 it's fixed.

http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/5.0.0_r1/android/graphics/drawable/Ripple.java#43

**Comment by DSteve595** [comment]
Any difference in `Ripple.java` between 5.0 and 5.1?

**Comment by ZieIony** [comment]
I was wrong, there's no difference in the code. Both animations should be the same. There are differences in handling alpha channel, drawing layer and there's new focused state for ripples in 5.1. If you wish, you can see that here:
http://androidxref.com/5.1.0_r1/xref/frameworks/base/graphics/java/android/graphics/drawable/Ripple.java
http://androidxref.com/5.0.0_r2/xref/frameworks/base/graphics/java/android/graphics/drawable/Ripple.java
http://androidxref.com/5.1.0_r1/xref/frameworks/base/graphics/java/android/graphics/drawable/RippleDrawable.java
http://androidxref.com/5.0.0_r2/xref/frameworks/base/graphics/java/android/graphics/drawable/RippleDrawable.java

**Comment by ZieIony** [comment]
The issue remains open, I would like to improve my ripples :)

**Comment by ZieIony** [comment]
I've just uploaded RippleDrawable with constants taken from the original ripples. I'm not sure if it's ok, on my phone it looks way to fast. Tomorrow I'll be able to test it a bit.

**Comment by ZieIony** [comment]
fixed in 0.7.2.

See: https://www.dropbox.com/s/2jp9nkin32487hx/ripple%20comparison.mp4?dl=0

**Comment by DSteve595** [comment]
The new Ripple looks pretty much the same as 5.1's, thanks!
