### ISSUE TITLE
Wrong return value at getChildDrawingOrder

### ISSUE THREAD

**Issue by aeai** [ZieIony/Carbon#60]
Hi there,

In the layout widgets the getChildDrawingOrder function returns a wrong drawing order and that messing up the shadows some cases. The function should tell which view need to be drawn in the "child" position, so the return value should be a childIndex. Your code is this:

``` java
return views != null ? views.indexOf(getChildAt(child)) : child;
```

which is returning an index from the views list instead of a proper child Index. With this the only time when the ordering works is when you add views to the layouts in the order of their elevation.

I think what should be there is this:

``` java
return views != null ? this.indexOfChild(views.get(child)) : child;
```

I tried it with the RelativeLayout and it seems to work properly.

By the way good library, keep up the good work :)

--Aeai

**Comment by ZieIony** [comment]
Hello and thank you for the kind words, I really appreciate that :)

As for the issue, you're right. I'm returning an index, where i-th child should be drawn. The method should return an index of a child to be drawn on i-th place. Nice finding!

**Comment by ZieIony** [comment]
Fixed, will be present in the next release (this week, 0.7.1)
