### ISSUE TITLE
2x anim out on circullar progress = narrower width

### ISSUE THREAD

**Issue by wrozwad** [ZieIony/Carbon#68]
When you fast 2x invoke `mProgressBar.setVisibility(View.INVISIBLE);` (I mean 2x during out animation) then after `mProgressBar.setVisibility(View.VISIBLE);` a circullar progress have narrower width. If you hide progres again with 2x `View.INVISIBLE` then they're again have narrower width.

**Comment by ZieIony** [comment]
This issue was addressed but not fixed as I would like. CircullarProgress won't change it's width anymore, but starting an animation in the middle of another one will result with a jump. Leaving open for further changes.

**Comment by ZieIony** [comment]
done
