### ISSUE TITLE
PagerTabStrip position with don't keep activities

### ISSUE THREAD

**Issue by wrozwad** [ZieIony/Carbon#69]
To reconstruct a bug:
1. In dev options enable "don't keep activites"
2. Run app with PagerTabStrip
3. Click home button
4. Return to your app

Then you can see that pager are moved left and first item are cropped:
![pagertabstrip bug](https://cloud.githubusercontent.com/assets/2025949/7198899/86845ec6-e4f0-11e4-9dcb-1db87e783d19.png)

**Comment by ZieIony** [comment]
PagerTabStrip doesn't save and restore it's state. If it's the issue, it should be easy to fix it.

**Comment by ZieIony** [comment]
I'm not sure, what's going on with the cropped item, but since last commit saving and restoring state works fine. I'm closing this issue as fixed in release 0.7.4
