### ISSUE TITLE
Inset changed callback for layouts

### ISSUE THREAD

**Issue by ZieIony** [ZieIony/Carbon#70]

**Comment by ZieIony** [comment]
Done. New listeners doesn't have parameters, but it's easy to get inset values from the changed view.

**Comment by DSteve595** [comment]
I may be doing something wrong, but there seems to be a problem with insets (not necessarily the callback, but this is the most relevant bug I could find).

Using ScrimInsetsLayout, I'm able to draw behind the status bar:
![image](https://cloud.githubusercontent.com/assets/1078569/7309481/ef0b3400-e9ec-11e4-90c4-f73ed0f1a886.png)

However, after switching to FrameLayout, the drawing starts below the inset:
![image](https://cloud.githubusercontent.com/assets/1078569/7309508/4274eca8-e9ed-11e4-948a-dbb8fc541208.png)

Here's my XML:

```
<carbon.widget.FrameLayout
        android:layout_width="260dp"
        android:layout_height="match_parent"
        android:layout_gravity="start"
        android:background="@android:color/white"
        android:fitsSystemWindows="true"
        app:carbon_elevation="4dp"
        app:carbon_insetColor="#4000">

        <fragment
            android:id="*removed*"
            android:name="*removed*"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </carbon.widget.FrameLayout>
```

Any idea what's up?

**Comment by ZieIony** [comment]
You have to set

```
  <item name="android:windowTranslucentStatus">true</item>
```

in your style and

```
 app:carbon_insetTop="0dp"
```

in your layout. The new approach is more flexible and allows one to modify all insets to be skipped or resized to any size. Check out the activity_drawer.xml file for more details.
