### ISSUE TITLE
Flickers on using radial Transistions

### ISSUE THREAD

**Issue by gabber12** [ZieIony/Carbon#74]
There are unusual flickers appearing while using radial transitions any way to avoid those.

**Comment by ZieIony** [comment]
This is a very good moment to ask such question, because I need radial transitions in one of my projects and I'm having issues with them as well. I'm thinking about rewriting radial transition using Canvas layers.

**Comment by gabber12** [comment]
Let me know if i can help.

**Comment by ZieIony** [comment]
Providing details about the device you're using may help. Also, if you can, please provide a screenshot, a video or a detailed description of the visual artifacts you're experiencing.

**Comment by ZieIony** [comment]
It should be better in 0.7.4. If not, please reopen the issue and provide more details.
