### ISSUE TITLE
Activated background selector only works on 5.0+

### ISSUE THREAD

**Issue by DSteve595** [ZieIony/Carbon#77]
I have this XML drawable:

```
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:state_activated="true">
        <color android:color="#1F000000" />
    </item>
    <item android:drawable="@android:color/transparent" />
</selector>
```

I'm setting it to a `carbon.widget.Button` via a style. It works perfectly on 5.0 and 5.1, but on KitKat, the activated color is never drawn. I also have a text selector that changes the text color when it's activated, and that works perfectly fine, so I know the activated state is being applied properly.

Lollipop (working):
![image](https://cloud.githubusercontent.com/assets/1078569/7333089/d347a7b0-eb2e-11e4-9c66-93819be0e571.png)

KitKat (not working):
![image](https://cloud.githubusercontent.com/assets/1078569/7333090/dd9d0796-eb2e-11e4-95da-f9e539c41b5c.png)

**Comment by ZieIony** [comment]
RippleDrawableCompat doesn't propagate state changes to it's children. Fixed in 0.8.0.
