### ISSUE TITLE
versions on GitHub (0.72) and MavenCentral(0.7.4)

### ISSUE THREAD

**Issue by NeverGivinUp** [ZieIony/Carbon#78]
There seem to be different versions of Carbon on GitHub and MavenCentral (according to the Link at the start of  README.md). Is that on purpose?

**Comment by ZieIony** [comment]
All Carbon users prefer Maven due to faster and easier integration with Android Studio projects. That's why I've been a little lazy and skipped these two releases. There's a larger release coming out after holidays (4th of May) and I will release that version on github as well.

**Comment by NeverGivinUp** [comment]
Well, it seems not _all_ Carbon users... I'm using Eclipse. And I'm way too far into the project to change IDEs or build stacks, even if they would be faster and easier in the long  run. So thanks for the coming update :-)
