### ISSUE TITLE
No resource found that matches the given name: attr 'windowNoTitle'.

### ISSUE THREAD

**Issue by iAviatorJose** [ZieIony/Carbon#83]
I am getting the following error:

D:\Tutorial-Android\CarbonAndroid\Carbon\carbon\src\main\res\values\styles.xml
Error:(79, 21) No resource found that matches the given name: attr 'windowNoTitle'.
Error:(79, 21) No resource found that matches the given name: attr 'windowNoTitle'.
Error:(79, 21) No resource found that matches the given name: attr 'windowNoTitle'.
Error:(79, 21) No resource found that matches the given name: attr 'windowNoTitle'.
Error:Execution failed for task ':carbon:processReleaseResources'.

> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
>     D:\SidAndro\adt-bundle-windows-x86_64-20140321\sdk\build-tools\21.1.2\aapt.exe package -f --no-crunch -I D:\SidAndro\adt-bundle-windows-x86_64-20140321\sdk\platforms\android-21\android.jar -M D:\Tutorial-Android\CarbonAndroid\Carbon\carbon\build\intermediates\bundles\release\AndroidManifest.xml -S D:\Tutorial-Android\CarbonAndroid\Carbon\carbon\build\intermediates\res\release -A D:\Tutorial-Android\CarbonAndroid\Carbon\carbon\build\intermediates\bundles\release\assets -m -J D:\Tutorial-Android\CarbonAndroid\Carbon\carbon\build\generated\source\r\release --custom-package carbon --non-constant-id -0 apk --output-text-symbols D:\Tutorial-Android\CarbonAndroid\Carbon\carbon\build\intermediates\bundles\release
> Error Code:
>     1
> Output:
>     D:\Tutorial-Android\CarbonAndroid\Carbon\carbon\build\intermediates\res\release\values\values.xml:1651: error: Error: No resource found that matches the given name: attr 'windowNoTitle'.
>     D:\Tutorial-Android\CarbonAndroid\Carbon\carbon\build\intermediates\res\release\values\values.xml:1731: error: Error: No resource found that matches the given name: attr 'windowNoTitle'.
>     D:\Tutorial-Android\CarbonAndroid\Carbon\carbon\build\intermediates\res\release\values\values.xml:1808: error: Error: No resource found that matches the given name: attr 'windowNoTitle'.
>     D:\Tutorial-Android\CarbonAndroid\Carbon\carbon\build\intermediates\res\release\values\values.xml:1884: error: Error: No resource found that matches the given name: attr 'windowNoTitle'.
> Information:BUILD FAILED

**Comment by ZieIony** [comment]
It's not really an issue with Carbon, but AppCompat. You have to update your project to use the most recent Google libraries, themes, etc. 'windowNoTitle' is a part of appcompat-v7:22.1.1
