### ISSUE TITLE
roboto fonts directory

### ISSUE THREAD

**Issue by NeverGivinUp** [ZieIony/Carbon#86]
currently the fonts are expected to be directly inside the assets directory. It is more common for the fonts to be in the fonts subdirectory of assets. Would you consider moving the fonts or creating a setter for the font path?

Also, in [my fist attempt at a wiki entry](https://github.com/ZieIony/Carbon/wiki/How-to-migrate-from-using-AppCompat-to-using-Carbon) I wrote, that it is necessary to copy the fonts from Carbon (or Google) to your own project. I'm not sure though, if that is correct or if I'm just lacking experience with Android development environments.

**Comment by ZieIony** [comment]
Good idea. I'll move and rename the files. It's also nice to have a way to specify custom fonts.

Copying fonts is done automatically - you don't have to do that. Gradle merges project folders including assets.

**Comment by ZieIony** [comment]
Done, see the most recent commit. Will be present in the upcoming release
