### ISSUE TITLE
keep crushing randomly

### ISSUE THREAD

**Issue by dev-myatminsoe** [ZieIony/Carbon#94]
Sometime it works. Sometime the app crushes.

java.lang.RuntimeException: Unable to start activity ComponentInfo{mm.technomation.mcontacts2/mm.technomation.mcontacts2.MainActivity}: android.view.InflateException: Binary XML file line #2: Error inflating class carbon.widget.LinearLayout

**Comment by ZieIony** [comment]
Could you please post the full stacktrace and the xml?

**Comment by ZieIony** [comment]
7 days without any comment. I'm unable to fix a bug without any additional information. Maybe it's something in the user's code?
