### ISSUE TITLE
PagerTabStrip: incorrect state restoring

### ISSUE THREAD

**Issue by dmitriigriazin** [ZieIony/Carbon#95]
I have a situation, when ViewPager has no content, so it's stays invisible for a while. However, on rotation PagerTabStrip still tries to get links to the content, getting NPE.

> Caused by: java.lang.NullPointerException
>             at carbon.widget.PagerTabStrip.setSelectedPage(PagerTabStrip.java:223)
>             at carbon.widget.PagerTabStrip.onRestoreInstanceState(PagerTabStrip.java:238)

**Comment by dmitriigriazin** [comment]
As temporary crutch, I've just overiden that method as:

``` java
@Override
    public void setSelectedPage(int position) {
       if (getViewPager() == null) return;
        super.setSelectedPage(position);
    }
```

**Comment by ZieIony** [comment]
fixed
